
#####用户好友
CREATE TABLE `UserFriend_0` (
  `id` int(11) NOT NULL auto_increment,
  `userId` int(11) NOT NULL,
  `friendId` int(11) NOT NULL,
  `friendName` varchar(50) NOT NULL COMMENT '好友名字',
  `friendType` int(11) NOT NULL COMMENT '好友类型',
  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',
  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',
  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;


#####用户好友请求数据
CREATE TABLE `UserFriendAsk` (
  `id` int(11) NOT NULL auto_increment,
  `userId` int(11) NOT NULL,
  `friendId` int(11) NOT NULL,
  `askAt` bigint(20) NOT NULL COMMENT '请求时间',
  `friendName` varchar(50) NOT NULL COMMENT '请求的好友名字',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `UserFriend_1`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_2`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_3`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_4`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_5`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_6`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_7`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_8`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_9`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_10`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_11`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_12`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_13`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_14`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_15`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_16`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_17`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_18`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_19`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_20`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_21`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_22`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_23`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_24`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_25`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_26`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_27`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_28`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_29`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_30`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_31`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_32`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_33`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_34`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_35`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_36`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_37`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_38`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_39`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_40`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_41`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_42`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_43`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_44`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_45`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_46`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_47`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_48`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_49`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_50`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_51`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_52`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_53`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_54`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_55`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_56`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_57`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_58`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_59`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_60`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_61`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_62`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_63`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_64`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_65`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_66`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_67`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_68`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_69`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_70`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_71`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_72`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_73`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_74`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_75`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_76`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_77`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_78`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_79`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_80`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_81`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_82`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_83`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_84`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_85`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_86`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_87`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_88`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_89`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_90`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_91`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_92`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_93`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_94`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_95`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_96`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_97`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_98`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `UserFriend_99`(`id` int(11) NOT NULL auto_increment,  `userId` int(11) NOT NULL,  `friendId` int(11) NOT NULL,  `friendName` varchar(50) NOT NULL COMMENT '好友名字',  `friendType` int(11) NOT NULL COMMENT '好友类型',  `gainHp` int(11) NOT NULL COMMENT '可以领取的体力值',  `sendAt` bigint(20) NOT NULL COMMENT '赠送时间',  `gainAt` bigint(20) NOT NULL COMMENT '获得时间',  PRIMARY KEY  (`id`),  UNIQUE KEY `uid_fid_index` (`userId`,`friendId`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
