// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: items.proto

package qxmobile.protobuf;

public final class ItemProtos {
  private ItemProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 itemId = 1;
    /**
     * <code>required int32 itemId = 1;</code>
     */
    boolean hasItemId();
    /**
     * <code>required int32 itemId = 1;</code>
     */
    int getItemId();

    // required int32 templateId = 2;
    /**
     * <code>required int32 templateId = 2;</code>
     */
    boolean hasTemplateId();
    /**
     * <code>required int32 templateId = 2;</code>
     */
    int getTemplateId();

    // required int32 num = 3;
    /**
     * <code>required int32 num = 3;</code>
     */
    boolean hasNum();
    /**
     * <code>required int32 num = 3;</code>
     */
    int getNum();

    // required int32 level = 4;
    /**
     * <code>required int32 level = 4;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 4;</code>
     */
    int getLevel();

    // required int32 id = 5;
    /**
     * <code>required int32 id = 5;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 5;</code>
     */
    int getId();

    // repeated int32 slots = 6;
    /**
     * <code>repeated int32 slots = 6;</code>
     */
    java.util.List<java.lang.Integer> getSlotsList();
    /**
     * <code>repeated int32 slots = 6;</code>
     */
    int getSlotsCount();
    /**
     * <code>repeated int32 slots = 6;</code>
     */
    int getSlots(int index);

    // required int32 status = 7;
    /**
     * <code>required int32 status = 7;</code>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 7;</code>
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.Item}
   */
  public static final class Item extends
      com.google.protobuf.GeneratedMessage
      implements ItemOrBuilder {
    // Use Item.newBuilder() to construct.
    private Item(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Item(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Item defaultInstance;
    public static Item getDefaultInstance() {
      return defaultInstance;
    }

    public Item getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Item(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              itemId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              templateId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              num_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              level_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              id_ = input.readInt32();
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                slots_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              slots_.add(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                slots_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                slots_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              status_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          slots_ = java.util.Collections.unmodifiableList(slots_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.ItemProtos.internal_static_qxmobile_protobuf_Item_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.ItemProtos.internal_static_qxmobile_protobuf_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.ItemProtos.Item.class, qxmobile.protobuf.ItemProtos.Item.Builder.class);
    }

    public static com.google.protobuf.Parser<Item> PARSER =
        new com.google.protobuf.AbstractParser<Item>() {
      public Item parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Item(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Item> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 itemId = 1;
    public static final int ITEMID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <code>required int32 itemId = 1;</code>
     */
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 itemId = 1;</code>
     */
    public int getItemId() {
      return itemId_;
    }

    // required int32 templateId = 2;
    public static final int TEMPLATEID_FIELD_NUMBER = 2;
    private int templateId_;
    /**
     * <code>required int32 templateId = 2;</code>
     */
    public boolean hasTemplateId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 templateId = 2;</code>
     */
    public int getTemplateId() {
      return templateId_;
    }

    // required int32 num = 3;
    public static final int NUM_FIELD_NUMBER = 3;
    private int num_;
    /**
     * <code>required int32 num = 3;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 num = 3;</code>
     */
    public int getNum() {
      return num_;
    }

    // required int32 level = 4;
    public static final int LEVEL_FIELD_NUMBER = 4;
    private int level_;
    /**
     * <code>required int32 level = 4;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 level = 4;</code>
     */
    public int getLevel() {
      return level_;
    }

    // required int32 id = 5;
    public static final int ID_FIELD_NUMBER = 5;
    private int id_;
    /**
     * <code>required int32 id = 5;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 id = 5;</code>
     */
    public int getId() {
      return id_;
    }

    // repeated int32 slots = 6;
    public static final int SLOTS_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Integer> slots_;
    /**
     * <code>repeated int32 slots = 6;</code>
     */
    public java.util.List<java.lang.Integer>
        getSlotsList() {
      return slots_;
    }
    /**
     * <code>repeated int32 slots = 6;</code>
     */
    public int getSlotsCount() {
      return slots_.size();
    }
    /**
     * <code>repeated int32 slots = 6;</code>
     */
    public int getSlots(int index) {
      return slots_.get(index);
    }

    // required int32 status = 7;
    public static final int STATUS_FIELD_NUMBER = 7;
    private int status_;
    /**
     * <code>required int32 status = 7;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 status = 7;</code>
     */
    public int getStatus() {
      return status_;
    }

    private void initFields() {
      itemId_ = 0;
      templateId_ = 0;
      num_ = 0;
      level_ = 0;
      id_ = 0;
      slots_ = java.util.Collections.emptyList();
      status_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasItemId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTemplateId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, itemId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, templateId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, num_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, level_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, id_);
      }
      for (int i = 0; i < slots_.size(); i++) {
        output.writeInt32(6, slots_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, templateId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, num_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, level_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < slots_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(slots_.get(i));
        }
        size += dataSize;
        size += 1 * getSlotsList().size();
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.ItemProtos.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.ItemProtos.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.ItemProtos.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.ItemProtos.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.ItemProtos.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.ItemProtos.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.ItemProtos.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.ItemProtos.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.ItemProtos.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.ItemProtos.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.ItemProtos.Item prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.Item}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.ItemProtos.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.ItemProtos.internal_static_qxmobile_protobuf_Item_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.ItemProtos.internal_static_qxmobile_protobuf_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.ItemProtos.Item.class, qxmobile.protobuf.ItemProtos.Item.Builder.class);
      }

      // Construct using qxmobile.protobuf.ItemProtos.Item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        itemId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        templateId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        slots_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.ItemProtos.internal_static_qxmobile_protobuf_Item_descriptor;
      }

      public qxmobile.protobuf.ItemProtos.Item getDefaultInstanceForType() {
        return qxmobile.protobuf.ItemProtos.Item.getDefaultInstance();
      }

      public qxmobile.protobuf.ItemProtos.Item build() {
        qxmobile.protobuf.ItemProtos.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.ItemProtos.Item buildPartial() {
        qxmobile.protobuf.ItemProtos.Item result = new qxmobile.protobuf.ItemProtos.Item(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.itemId_ = itemId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.templateId_ = templateId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.num_ = num_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          slots_ = java.util.Collections.unmodifiableList(slots_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.slots_ = slots_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.ItemProtos.Item) {
          return mergeFrom((qxmobile.protobuf.ItemProtos.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.ItemProtos.Item other) {
        if (other == qxmobile.protobuf.ItemProtos.Item.getDefaultInstance()) return this;
        if (other.hasItemId()) {
          setItemId(other.getItemId());
        }
        if (other.hasTemplateId()) {
          setTemplateId(other.getTemplateId());
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.slots_.isEmpty()) {
          if (slots_.isEmpty()) {
            slots_ = other.slots_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureSlotsIsMutable();
            slots_.addAll(other.slots_);
          }
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasItemId()) {
          
          return false;
        }
        if (!hasTemplateId()) {
          
          return false;
        }
        if (!hasNum()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.ItemProtos.Item parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.ItemProtos.Item) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 itemId = 1;
      private int itemId_ ;
      /**
       * <code>required int32 itemId = 1;</code>
       */
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 itemId = 1;</code>
       */
      public int getItemId() {
        return itemId_;
      }
      /**
       * <code>required int32 itemId = 1;</code>
       */
      public Builder setItemId(int value) {
        bitField0_ |= 0x00000001;
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 itemId = 1;</code>
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemId_ = 0;
        onChanged();
        return this;
      }

      // required int32 templateId = 2;
      private int templateId_ ;
      /**
       * <code>required int32 templateId = 2;</code>
       */
      public boolean hasTemplateId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 templateId = 2;</code>
       */
      public int getTemplateId() {
        return templateId_;
      }
      /**
       * <code>required int32 templateId = 2;</code>
       */
      public Builder setTemplateId(int value) {
        bitField0_ |= 0x00000002;
        templateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 templateId = 2;</code>
       */
      public Builder clearTemplateId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        templateId_ = 0;
        onChanged();
        return this;
      }

      // required int32 num = 3;
      private int num_ ;
      /**
       * <code>required int32 num = 3;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 num = 3;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>required int32 num = 3;</code>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000004;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num = 3;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        num_ = 0;
        onChanged();
        return this;
      }

      // required int32 level = 4;
      private int level_ ;
      /**
       * <code>required int32 level = 4;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 level = 4;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 4;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000008;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 4;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        onChanged();
        return this;
      }

      // required int32 id = 5;
      private int id_ ;
      /**
       * <code>required int32 id = 5;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 id = 5;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 5;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000010;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 5;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        id_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 slots = 6;
      private java.util.List<java.lang.Integer> slots_ = java.util.Collections.emptyList();
      private void ensureSlotsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          slots_ = new java.util.ArrayList<java.lang.Integer>(slots_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated int32 slots = 6;</code>
       */
      public java.util.List<java.lang.Integer>
          getSlotsList() {
        return java.util.Collections.unmodifiableList(slots_);
      }
      /**
       * <code>repeated int32 slots = 6;</code>
       */
      public int getSlotsCount() {
        return slots_.size();
      }
      /**
       * <code>repeated int32 slots = 6;</code>
       */
      public int getSlots(int index) {
        return slots_.get(index);
      }
      /**
       * <code>repeated int32 slots = 6;</code>
       */
      public Builder setSlots(
          int index, int value) {
        ensureSlotsIsMutable();
        slots_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 slots = 6;</code>
       */
      public Builder addSlots(int value) {
        ensureSlotsIsMutable();
        slots_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 slots = 6;</code>
       */
      public Builder addAllSlots(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSlotsIsMutable();
        super.addAll(values, slots_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 slots = 6;</code>
       */
      public Builder clearSlots() {
        slots_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      // required int32 status = 7;
      private int status_ ;
      /**
       * <code>required int32 status = 7;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 status = 7;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 7;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000040;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 7;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000040);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.Item)
    }

    static {
      defaultInstance = new Item(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.Item)
  }

  public interface BagOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 num = 1;
    /**
     * <code>required int32 num = 1;</code>
     */
    boolean hasNum();
    /**
     * <code>required int32 num = 1;</code>
     */
    int getNum();

    // repeated .qxmobile.protobuf.Item item = 2;
    /**
     * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
     */
    java.util.List<qxmobile.protobuf.ItemProtos.Item> 
        getItemList();
    /**
     * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
     */
    qxmobile.protobuf.ItemProtos.Item getItem(int index);
    /**
     * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
     */
    int getItemCount();
    /**
     * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
     */
    java.util.List<? extends qxmobile.protobuf.ItemProtos.ItemOrBuilder> 
        getItemOrBuilderList();
    /**
     * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
     */
    qxmobile.protobuf.ItemProtos.ItemOrBuilder getItemOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.Bag}
   */
  public static final class Bag extends
      com.google.protobuf.GeneratedMessage
      implements BagOrBuilder {
    // Use Bag.newBuilder() to construct.
    private Bag(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Bag(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Bag defaultInstance;
    public static Bag getDefaultInstance() {
      return defaultInstance;
    }

    public Bag getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Bag(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              num_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                item_ = new java.util.ArrayList<qxmobile.protobuf.ItemProtos.Item>();
                mutable_bitField0_ |= 0x00000002;
              }
              item_.add(input.readMessage(qxmobile.protobuf.ItemProtos.Item.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          item_ = java.util.Collections.unmodifiableList(item_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.ItemProtos.internal_static_qxmobile_protobuf_Bag_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.ItemProtos.internal_static_qxmobile_protobuf_Bag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.ItemProtos.Bag.class, qxmobile.protobuf.ItemProtos.Bag.Builder.class);
    }

    public static com.google.protobuf.Parser<Bag> PARSER =
        new com.google.protobuf.AbstractParser<Bag>() {
      public Bag parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Bag(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Bag> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 num = 1;
    public static final int NUM_FIELD_NUMBER = 1;
    private int num_;
    /**
     * <code>required int32 num = 1;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 num = 1;</code>
     */
    public int getNum() {
      return num_;
    }

    // repeated .qxmobile.protobuf.Item item = 2;
    public static final int ITEM_FIELD_NUMBER = 2;
    private java.util.List<qxmobile.protobuf.ItemProtos.Item> item_;
    /**
     * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
     */
    public java.util.List<qxmobile.protobuf.ItemProtos.Item> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
     */
    public java.util.List<? extends qxmobile.protobuf.ItemProtos.ItemOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
     */
    public qxmobile.protobuf.ItemProtos.Item getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
     */
    public qxmobile.protobuf.ItemProtos.ItemOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }

    private void initFields() {
      num_ = 0;
      item_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getItemCount(); i++) {
        if (!getItem(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, num_);
      }
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(2, item_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, num_);
      }
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, item_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.ItemProtos.Bag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.ItemProtos.Bag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.ItemProtos.Bag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.ItemProtos.Bag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.ItemProtos.Bag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.ItemProtos.Bag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.ItemProtos.Bag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.ItemProtos.Bag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.ItemProtos.Bag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.ItemProtos.Bag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.ItemProtos.Bag prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.Bag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.ItemProtos.BagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.ItemProtos.internal_static_qxmobile_protobuf_Bag_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.ItemProtos.internal_static_qxmobile_protobuf_Bag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.ItemProtos.Bag.class, qxmobile.protobuf.ItemProtos.Bag.Builder.class);
      }

      // Construct using qxmobile.protobuf.ItemProtos.Bag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.ItemProtos.internal_static_qxmobile_protobuf_Bag_descriptor;
      }

      public qxmobile.protobuf.ItemProtos.Bag getDefaultInstanceForType() {
        return qxmobile.protobuf.ItemProtos.Bag.getDefaultInstance();
      }

      public qxmobile.protobuf.ItemProtos.Bag build() {
        qxmobile.protobuf.ItemProtos.Bag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.ItemProtos.Bag buildPartial() {
        qxmobile.protobuf.ItemProtos.Bag result = new qxmobile.protobuf.ItemProtos.Bag(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.num_ = num_;
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.ItemProtos.Bag) {
          return mergeFrom((qxmobile.protobuf.ItemProtos.Bag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.ItemProtos.Bag other) {
        if (other == qxmobile.protobuf.ItemProtos.Bag.getDefaultInstance()) return this;
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNum()) {
          
          return false;
        }
        for (int i = 0; i < getItemCount(); i++) {
          if (!getItem(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.ItemProtos.Bag parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.ItemProtos.Bag) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 num = 1;
      private int num_ ;
      /**
       * <code>required int32 num = 1;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 num = 1;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>required int32 num = 1;</code>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000001;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num = 1;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = 0;
        onChanged();
        return this;
      }

      // repeated .qxmobile.protobuf.Item item = 2;
      private java.util.List<qxmobile.protobuf.ItemProtos.Item> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          item_ = new java.util.ArrayList<qxmobile.protobuf.ItemProtos.Item>(item_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          qxmobile.protobuf.ItemProtos.Item, qxmobile.protobuf.ItemProtos.Item.Builder, qxmobile.protobuf.ItemProtos.ItemOrBuilder> itemBuilder_;

      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public java.util.List<qxmobile.protobuf.ItemProtos.Item> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public qxmobile.protobuf.ItemProtos.Item getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public Builder setItem(
          int index, qxmobile.protobuf.ItemProtos.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public Builder setItem(
          int index, qxmobile.protobuf.ItemProtos.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public Builder addItem(qxmobile.protobuf.ItemProtos.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public Builder addItem(
          int index, qxmobile.protobuf.ItemProtos.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public Builder addItem(
          qxmobile.protobuf.ItemProtos.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public Builder addItem(
          int index, qxmobile.protobuf.ItemProtos.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends qxmobile.protobuf.ItemProtos.Item> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          super.addAll(values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public qxmobile.protobuf.ItemProtos.Item.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public qxmobile.protobuf.ItemProtos.ItemOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public java.util.List<? extends qxmobile.protobuf.ItemProtos.ItemOrBuilder> 
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public qxmobile.protobuf.ItemProtos.Item.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            qxmobile.protobuf.ItemProtos.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public qxmobile.protobuf.ItemProtos.Item.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, qxmobile.protobuf.ItemProtos.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .qxmobile.protobuf.Item item = 2;</code>
       */
      public java.util.List<qxmobile.protobuf.ItemProtos.Item.Builder> 
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          qxmobile.protobuf.ItemProtos.Item, qxmobile.protobuf.ItemProtos.Item.Builder, qxmobile.protobuf.ItemProtos.ItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              qxmobile.protobuf.ItemProtos.Item, qxmobile.protobuf.ItemProtos.Item.Builder, qxmobile.protobuf.ItemProtos.ItemOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.Bag)
    }

    static {
      defaultInstance = new Bag(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.Bag)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_Item_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_Item_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_Bag_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_Bag_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013items.proto\022\021qxmobile.protobuf\"q\n\004Item" +
      "\022\016\n\006itemId\030\001 \002(\005\022\022\n\ntemplateId\030\002 \002(\005\022\013\n\003" +
      "num\030\003 \002(\005\022\r\n\005level\030\004 \002(\005\022\n\n\002id\030\005 \002(\005\022\r\n\005" +
      "slots\030\006 \003(\005\022\016\n\006status\030\007 \002(\005\"9\n\003Bag\022\013\n\003nu" +
      "m\030\001 \002(\005\022%\n\004item\030\002 \003(\0132\027.qxmobile.protobu" +
      "f.ItemB\014B\nItemProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_qxmobile_protobuf_Item_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_qxmobile_protobuf_Item_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_Item_descriptor,
              new java.lang.String[] { "ItemId", "TemplateId", "Num", "Level", "Id", "Slots", "Status", });
          internal_static_qxmobile_protobuf_Bag_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_qxmobile_protobuf_Bag_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_Bag_descriptor,
              new java.lang.String[] { "Num", "Item", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
