// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JiNengPeiYang.proto

package qxmobile.protobuf;

public final class JiNengPeiYang {
  private JiNengPeiYang() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetJiNengPeiYangQualityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .qxmobile.protobuf.JiNengQuality jn = 1;
    /**
     * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
     *
     * <pre>
     * 技能培养阶段
     * </pre>
     */
    java.util.List<qxmobile.protobuf.JiNengPeiYang.JiNengQuality> 
        getJnList();
    /**
     * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
     *
     * <pre>
     * 技能培养阶段
     * </pre>
     */
    qxmobile.protobuf.JiNengPeiYang.JiNengQuality getJn(int index);
    /**
     * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
     *
     * <pre>
     * 技能培养阶段
     * </pre>
     */
    int getJnCount();
    /**
     * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
     *
     * <pre>
     * 技能培养阶段
     * </pre>
     */
    java.util.List<? extends qxmobile.protobuf.JiNengPeiYang.JiNengQualityOrBuilder> 
        getJnOrBuilderList();
    /**
     * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
     *
     * <pre>
     * 技能培养阶段
     * </pre>
     */
    qxmobile.protobuf.JiNengPeiYang.JiNengQualityOrBuilder getJnOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.GetJiNengPeiYangQuality}
   *
   * <pre>
   * 请求技能养成阶段，请求协议号4250，相应协议号4251
   * </pre>
   */
  public static final class GetJiNengPeiYangQuality extends
      com.google.protobuf.GeneratedMessage
      implements GetJiNengPeiYangQualityOrBuilder {
    // Use GetJiNengPeiYangQuality.newBuilder() to construct.
    private GetJiNengPeiYangQuality(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetJiNengPeiYangQuality(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetJiNengPeiYangQuality defaultInstance;
    public static GetJiNengPeiYangQuality getDefaultInstance() {
      return defaultInstance;
    }

    public GetJiNengPeiYangQuality getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetJiNengPeiYangQuality(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                jn_ = new java.util.ArrayList<qxmobile.protobuf.JiNengPeiYang.JiNengQuality>();
                mutable_bitField0_ |= 0x00000001;
              }
              jn_.add(input.readMessage(qxmobile.protobuf.JiNengPeiYang.JiNengQuality.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          jn_ = java.util.Collections.unmodifiableList(jn_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_GetJiNengPeiYangQuality_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_GetJiNengPeiYangQuality_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality.class, qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality.Builder.class);
    }

    public static com.google.protobuf.Parser<GetJiNengPeiYangQuality> PARSER =
        new com.google.protobuf.AbstractParser<GetJiNengPeiYangQuality>() {
      public GetJiNengPeiYangQuality parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetJiNengPeiYangQuality(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetJiNengPeiYangQuality> getParserForType() {
      return PARSER;
    }

    // repeated .qxmobile.protobuf.JiNengQuality jn = 1;
    public static final int JN_FIELD_NUMBER = 1;
    private java.util.List<qxmobile.protobuf.JiNengPeiYang.JiNengQuality> jn_;
    /**
     * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
     *
     * <pre>
     * 技能培养阶段
     * </pre>
     */
    public java.util.List<qxmobile.protobuf.JiNengPeiYang.JiNengQuality> getJnList() {
      return jn_;
    }
    /**
     * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
     *
     * <pre>
     * 技能培养阶段
     * </pre>
     */
    public java.util.List<? extends qxmobile.protobuf.JiNengPeiYang.JiNengQualityOrBuilder> 
        getJnOrBuilderList() {
      return jn_;
    }
    /**
     * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
     *
     * <pre>
     * 技能培养阶段
     * </pre>
     */
    public int getJnCount() {
      return jn_.size();
    }
    /**
     * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
     *
     * <pre>
     * 技能培养阶段
     * </pre>
     */
    public qxmobile.protobuf.JiNengPeiYang.JiNengQuality getJn(int index) {
      return jn_.get(index);
    }
    /**
     * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
     *
     * <pre>
     * 技能培养阶段
     * </pre>
     */
    public qxmobile.protobuf.JiNengPeiYang.JiNengQualityOrBuilder getJnOrBuilder(
        int index) {
      return jn_.get(index);
    }

    private void initFields() {
      jn_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getJnCount(); i++) {
        if (!getJn(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < jn_.size(); i++) {
        output.writeMessage(1, jn_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < jn_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, jn_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.GetJiNengPeiYangQuality}
     *
     * <pre>
     * 请求技能养成阶段，请求协议号4250，相应协议号4251
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQualityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_GetJiNengPeiYangQuality_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_GetJiNengPeiYangQuality_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality.class, qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality.Builder.class);
      }

      // Construct using qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getJnFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (jnBuilder_ == null) {
          jn_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          jnBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_GetJiNengPeiYangQuality_descriptor;
      }

      public qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality getDefaultInstanceForType() {
        return qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality.getDefaultInstance();
      }

      public qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality build() {
        qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality buildPartial() {
        qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality result = new qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality(this);
        int from_bitField0_ = bitField0_;
        if (jnBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            jn_ = java.util.Collections.unmodifiableList(jn_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.jn_ = jn_;
        } else {
          result.jn_ = jnBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality) {
          return mergeFrom((qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality other) {
        if (other == qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality.getDefaultInstance()) return this;
        if (jnBuilder_ == null) {
          if (!other.jn_.isEmpty()) {
            if (jn_.isEmpty()) {
              jn_ = other.jn_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureJnIsMutable();
              jn_.addAll(other.jn_);
            }
            onChanged();
          }
        } else {
          if (!other.jn_.isEmpty()) {
            if (jnBuilder_.isEmpty()) {
              jnBuilder_.dispose();
              jnBuilder_ = null;
              jn_ = other.jn_;
              bitField0_ = (bitField0_ & ~0x00000001);
              jnBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getJnFieldBuilder() : null;
            } else {
              jnBuilder_.addAllMessages(other.jn_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getJnCount(); i++) {
          if (!getJn(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.JiNengPeiYang.GetJiNengPeiYangQuality) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .qxmobile.protobuf.JiNengQuality jn = 1;
      private java.util.List<qxmobile.protobuf.JiNengPeiYang.JiNengQuality> jn_ =
        java.util.Collections.emptyList();
      private void ensureJnIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          jn_ = new java.util.ArrayList<qxmobile.protobuf.JiNengPeiYang.JiNengQuality>(jn_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          qxmobile.protobuf.JiNengPeiYang.JiNengQuality, qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder, qxmobile.protobuf.JiNengPeiYang.JiNengQualityOrBuilder> jnBuilder_;

      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public java.util.List<qxmobile.protobuf.JiNengPeiYang.JiNengQuality> getJnList() {
        if (jnBuilder_ == null) {
          return java.util.Collections.unmodifiableList(jn_);
        } else {
          return jnBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public int getJnCount() {
        if (jnBuilder_ == null) {
          return jn_.size();
        } else {
          return jnBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public qxmobile.protobuf.JiNengPeiYang.JiNengQuality getJn(int index) {
        if (jnBuilder_ == null) {
          return jn_.get(index);
        } else {
          return jnBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public Builder setJn(
          int index, qxmobile.protobuf.JiNengPeiYang.JiNengQuality value) {
        if (jnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJnIsMutable();
          jn_.set(index, value);
          onChanged();
        } else {
          jnBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public Builder setJn(
          int index, qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder builderForValue) {
        if (jnBuilder_ == null) {
          ensureJnIsMutable();
          jn_.set(index, builderForValue.build());
          onChanged();
        } else {
          jnBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public Builder addJn(qxmobile.protobuf.JiNengPeiYang.JiNengQuality value) {
        if (jnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJnIsMutable();
          jn_.add(value);
          onChanged();
        } else {
          jnBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public Builder addJn(
          int index, qxmobile.protobuf.JiNengPeiYang.JiNengQuality value) {
        if (jnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJnIsMutable();
          jn_.add(index, value);
          onChanged();
        } else {
          jnBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public Builder addJn(
          qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder builderForValue) {
        if (jnBuilder_ == null) {
          ensureJnIsMutable();
          jn_.add(builderForValue.build());
          onChanged();
        } else {
          jnBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public Builder addJn(
          int index, qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder builderForValue) {
        if (jnBuilder_ == null) {
          ensureJnIsMutable();
          jn_.add(index, builderForValue.build());
          onChanged();
        } else {
          jnBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public Builder addAllJn(
          java.lang.Iterable<? extends qxmobile.protobuf.JiNengPeiYang.JiNengQuality> values) {
        if (jnBuilder_ == null) {
          ensureJnIsMutable();
          super.addAll(values, jn_);
          onChanged();
        } else {
          jnBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public Builder clearJn() {
        if (jnBuilder_ == null) {
          jn_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          jnBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public Builder removeJn(int index) {
        if (jnBuilder_ == null) {
          ensureJnIsMutable();
          jn_.remove(index);
          onChanged();
        } else {
          jnBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder getJnBuilder(
          int index) {
        return getJnFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public qxmobile.protobuf.JiNengPeiYang.JiNengQualityOrBuilder getJnOrBuilder(
          int index) {
        if (jnBuilder_ == null) {
          return jn_.get(index);  } else {
          return jnBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public java.util.List<? extends qxmobile.protobuf.JiNengPeiYang.JiNengQualityOrBuilder> 
           getJnOrBuilderList() {
        if (jnBuilder_ != null) {
          return jnBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(jn_);
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder addJnBuilder() {
        return getJnFieldBuilder().addBuilder(
            qxmobile.protobuf.JiNengPeiYang.JiNengQuality.getDefaultInstance());
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder addJnBuilder(
          int index) {
        return getJnFieldBuilder().addBuilder(
            index, qxmobile.protobuf.JiNengPeiYang.JiNengQuality.getDefaultInstance());
      }
      /**
       * <code>repeated .qxmobile.protobuf.JiNengQuality jn = 1;</code>
       *
       * <pre>
       * 技能培养阶段
       * </pre>
       */
      public java.util.List<qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder> 
           getJnBuilderList() {
        return getJnFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          qxmobile.protobuf.JiNengPeiYang.JiNengQuality, qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder, qxmobile.protobuf.JiNengPeiYang.JiNengQualityOrBuilder> 
          getJnFieldBuilder() {
        if (jnBuilder_ == null) {
          jnBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              qxmobile.protobuf.JiNengPeiYang.JiNengQuality, qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder, qxmobile.protobuf.JiNengPeiYang.JiNengQualityOrBuilder>(
                  jn_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          jn_ = null;
        }
        return jnBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.GetJiNengPeiYangQuality)
    }

    static {
      defaultInstance = new GetJiNengPeiYangQuality(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.GetJiNengPeiYangQuality)
  }

  public interface JiNengQualityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 wuqiType = 1;
    /**
     * <code>required int32 wuqiType = 1;</code>
     *
     * <pre>
     * 武器类型	
     * </pre>
     */
    boolean hasWuqiType();
    /**
     * <code>required int32 wuqiType = 1;</code>
     *
     * <pre>
     * 武器类型	
     * </pre>
     */
    int getWuqiType();

    // required int32 jinengType = 2;
    /**
     * <code>required int32 jinengType = 2;</code>
     *
     * <pre>
     * 技能类型	
     * </pre>
     */
    boolean hasJinengType();
    /**
     * <code>required int32 jinengType = 2;</code>
     *
     * <pre>
     * 技能类型	
     * </pre>
     */
    int getJinengType();

    // required int32 quality = 3;
    /**
     * <code>required int32 quality = 3;</code>
     *
     * <pre>
     * 突破次数(0,1,2)
     * </pre>
     */
    boolean hasQuality();
    /**
     * <code>required int32 quality = 3;</code>
     *
     * <pre>
     * 突破次数(0,1,2)
     * </pre>
     */
    int getQuality();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.JiNengQuality}
   */
  public static final class JiNengQuality extends
      com.google.protobuf.GeneratedMessage
      implements JiNengQualityOrBuilder {
    // Use JiNengQuality.newBuilder() to construct.
    private JiNengQuality(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JiNengQuality(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JiNengQuality defaultInstance;
    public static JiNengQuality getDefaultInstance() {
      return defaultInstance;
    }

    public JiNengQuality getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JiNengQuality(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              wuqiType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              jinengType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              quality_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_JiNengQuality_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_JiNengQuality_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.JiNengPeiYang.JiNengQuality.class, qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder.class);
    }

    public static com.google.protobuf.Parser<JiNengQuality> PARSER =
        new com.google.protobuf.AbstractParser<JiNengQuality>() {
      public JiNengQuality parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JiNengQuality(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JiNengQuality> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 wuqiType = 1;
    public static final int WUQITYPE_FIELD_NUMBER = 1;
    private int wuqiType_;
    /**
     * <code>required int32 wuqiType = 1;</code>
     *
     * <pre>
     * 武器类型	
     * </pre>
     */
    public boolean hasWuqiType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 wuqiType = 1;</code>
     *
     * <pre>
     * 武器类型	
     * </pre>
     */
    public int getWuqiType() {
      return wuqiType_;
    }

    // required int32 jinengType = 2;
    public static final int JINENGTYPE_FIELD_NUMBER = 2;
    private int jinengType_;
    /**
     * <code>required int32 jinengType = 2;</code>
     *
     * <pre>
     * 技能类型	
     * </pre>
     */
    public boolean hasJinengType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 jinengType = 2;</code>
     *
     * <pre>
     * 技能类型	
     * </pre>
     */
    public int getJinengType() {
      return jinengType_;
    }

    // required int32 quality = 3;
    public static final int QUALITY_FIELD_NUMBER = 3;
    private int quality_;
    /**
     * <code>required int32 quality = 3;</code>
     *
     * <pre>
     * 突破次数(0,1,2)
     * </pre>
     */
    public boolean hasQuality() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 quality = 3;</code>
     *
     * <pre>
     * 突破次数(0,1,2)
     * </pre>
     */
    public int getQuality() {
      return quality_;
    }

    private void initFields() {
      wuqiType_ = 0;
      jinengType_ = 0;
      quality_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasWuqiType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJinengType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuality()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, wuqiType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, jinengType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, quality_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, wuqiType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, jinengType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, quality_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.JiNengPeiYang.JiNengQuality parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JiNengPeiYang.JiNengQuality parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.JiNengQuality parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JiNengPeiYang.JiNengQuality parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.JiNengQuality parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.JiNengQuality parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.JiNengQuality parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.JiNengQuality parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.JiNengQuality parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.JiNengQuality parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.JiNengPeiYang.JiNengQuality prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.JiNengQuality}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.JiNengPeiYang.JiNengQualityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_JiNengQuality_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_JiNengQuality_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.JiNengPeiYang.JiNengQuality.class, qxmobile.protobuf.JiNengPeiYang.JiNengQuality.Builder.class);
      }

      // Construct using qxmobile.protobuf.JiNengPeiYang.JiNengQuality.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        wuqiType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        jinengType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        quality_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_JiNengQuality_descriptor;
      }

      public qxmobile.protobuf.JiNengPeiYang.JiNengQuality getDefaultInstanceForType() {
        return qxmobile.protobuf.JiNengPeiYang.JiNengQuality.getDefaultInstance();
      }

      public qxmobile.protobuf.JiNengPeiYang.JiNengQuality build() {
        qxmobile.protobuf.JiNengPeiYang.JiNengQuality result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.JiNengPeiYang.JiNengQuality buildPartial() {
        qxmobile.protobuf.JiNengPeiYang.JiNengQuality result = new qxmobile.protobuf.JiNengPeiYang.JiNengQuality(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.wuqiType_ = wuqiType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jinengType_ = jinengType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.quality_ = quality_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.JiNengPeiYang.JiNengQuality) {
          return mergeFrom((qxmobile.protobuf.JiNengPeiYang.JiNengQuality)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.JiNengPeiYang.JiNengQuality other) {
        if (other == qxmobile.protobuf.JiNengPeiYang.JiNengQuality.getDefaultInstance()) return this;
        if (other.hasWuqiType()) {
          setWuqiType(other.getWuqiType());
        }
        if (other.hasJinengType()) {
          setJinengType(other.getJinengType());
        }
        if (other.hasQuality()) {
          setQuality(other.getQuality());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWuqiType()) {
          
          return false;
        }
        if (!hasJinengType()) {
          
          return false;
        }
        if (!hasQuality()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.JiNengPeiYang.JiNengQuality parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.JiNengPeiYang.JiNengQuality) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 wuqiType = 1;
      private int wuqiType_ ;
      /**
       * <code>required int32 wuqiType = 1;</code>
       *
       * <pre>
       * 武器类型	
       * </pre>
       */
      public boolean hasWuqiType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 wuqiType = 1;</code>
       *
       * <pre>
       * 武器类型	
       * </pre>
       */
      public int getWuqiType() {
        return wuqiType_;
      }
      /**
       * <code>required int32 wuqiType = 1;</code>
       *
       * <pre>
       * 武器类型	
       * </pre>
       */
      public Builder setWuqiType(int value) {
        bitField0_ |= 0x00000001;
        wuqiType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 wuqiType = 1;</code>
       *
       * <pre>
       * 武器类型	
       * </pre>
       */
      public Builder clearWuqiType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        wuqiType_ = 0;
        onChanged();
        return this;
      }

      // required int32 jinengType = 2;
      private int jinengType_ ;
      /**
       * <code>required int32 jinengType = 2;</code>
       *
       * <pre>
       * 技能类型	
       * </pre>
       */
      public boolean hasJinengType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 jinengType = 2;</code>
       *
       * <pre>
       * 技能类型	
       * </pre>
       */
      public int getJinengType() {
        return jinengType_;
      }
      /**
       * <code>required int32 jinengType = 2;</code>
       *
       * <pre>
       * 技能类型	
       * </pre>
       */
      public Builder setJinengType(int value) {
        bitField0_ |= 0x00000002;
        jinengType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 jinengType = 2;</code>
       *
       * <pre>
       * 技能类型	
       * </pre>
       */
      public Builder clearJinengType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jinengType_ = 0;
        onChanged();
        return this;
      }

      // required int32 quality = 3;
      private int quality_ ;
      /**
       * <code>required int32 quality = 3;</code>
       *
       * <pre>
       * 突破次数(0,1,2)
       * </pre>
       */
      public boolean hasQuality() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 quality = 3;</code>
       *
       * <pre>
       * 突破次数(0,1,2)
       * </pre>
       */
      public int getQuality() {
        return quality_;
      }
      /**
       * <code>required int32 quality = 3;</code>
       *
       * <pre>
       * 突破次数(0,1,2)
       * </pre>
       */
      public Builder setQuality(int value) {
        bitField0_ |= 0x00000004;
        quality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 quality = 3;</code>
       *
       * <pre>
       * 突破次数(0,1,2)
       * </pre>
       */
      public Builder clearQuality() {
        bitField0_ = (bitField0_ & ~0x00000004);
        quality_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.JiNengQuality)
    }

    static {
      defaultInstance = new JiNengQuality(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.JiNengQuality)
  }

  public interface UpgradeJiNengReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 wuqiType = 1;
    /**
     * <code>required int32 wuqiType = 1;</code>
     *
     * <pre>
     * 武器类型	
     * </pre>
     */
    boolean hasWuqiType();
    /**
     * <code>required int32 wuqiType = 1;</code>
     *
     * <pre>
     * 武器类型	
     * </pre>
     */
    int getWuqiType();

    // required int32 jinengType = 2;
    /**
     * <code>required int32 jinengType = 2;</code>
     *
     * <pre>
     * 技能类型	
     * </pre>
     */
    boolean hasJinengType();
    /**
     * <code>required int32 jinengType = 2;</code>
     *
     * <pre>
     * 技能类型	
     * </pre>
     */
    int getJinengType();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.UpgradeJiNengReq}
   *
   * <pre>
   * 突破技能请求，协议号4252
   * </pre>
   */
  public static final class UpgradeJiNengReq extends
      com.google.protobuf.GeneratedMessage
      implements UpgradeJiNengReqOrBuilder {
    // Use UpgradeJiNengReq.newBuilder() to construct.
    private UpgradeJiNengReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UpgradeJiNengReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UpgradeJiNengReq defaultInstance;
    public static UpgradeJiNengReq getDefaultInstance() {
      return defaultInstance;
    }

    public UpgradeJiNengReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UpgradeJiNengReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              wuqiType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              jinengType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_UpgradeJiNengReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_UpgradeJiNengReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq.class, qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq.Builder.class);
    }

    public static com.google.protobuf.Parser<UpgradeJiNengReq> PARSER =
        new com.google.protobuf.AbstractParser<UpgradeJiNengReq>() {
      public UpgradeJiNengReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpgradeJiNengReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UpgradeJiNengReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 wuqiType = 1;
    public static final int WUQITYPE_FIELD_NUMBER = 1;
    private int wuqiType_;
    /**
     * <code>required int32 wuqiType = 1;</code>
     *
     * <pre>
     * 武器类型	
     * </pre>
     */
    public boolean hasWuqiType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 wuqiType = 1;</code>
     *
     * <pre>
     * 武器类型	
     * </pre>
     */
    public int getWuqiType() {
      return wuqiType_;
    }

    // required int32 jinengType = 2;
    public static final int JINENGTYPE_FIELD_NUMBER = 2;
    private int jinengType_;
    /**
     * <code>required int32 jinengType = 2;</code>
     *
     * <pre>
     * 技能类型	
     * </pre>
     */
    public boolean hasJinengType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 jinengType = 2;</code>
     *
     * <pre>
     * 技能类型	
     * </pre>
     */
    public int getJinengType() {
      return jinengType_;
    }

    private void initFields() {
      wuqiType_ = 0;
      jinengType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasWuqiType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJinengType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, wuqiType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, jinengType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, wuqiType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, jinengType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.UpgradeJiNengReq}
     *
     * <pre>
     * 突破技能请求，协议号4252
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_UpgradeJiNengReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_UpgradeJiNengReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq.class, qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq.Builder.class);
      }

      // Construct using qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        wuqiType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        jinengType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_UpgradeJiNengReq_descriptor;
      }

      public qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq getDefaultInstanceForType() {
        return qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq.getDefaultInstance();
      }

      public qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq build() {
        qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq buildPartial() {
        qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq result = new qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.wuqiType_ = wuqiType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jinengType_ = jinengType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq) {
          return mergeFrom((qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq other) {
        if (other == qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq.getDefaultInstance()) return this;
        if (other.hasWuqiType()) {
          setWuqiType(other.getWuqiType());
        }
        if (other.hasJinengType()) {
          setJinengType(other.getJinengType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWuqiType()) {
          
          return false;
        }
        if (!hasJinengType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 wuqiType = 1;
      private int wuqiType_ ;
      /**
       * <code>required int32 wuqiType = 1;</code>
       *
       * <pre>
       * 武器类型	
       * </pre>
       */
      public boolean hasWuqiType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 wuqiType = 1;</code>
       *
       * <pre>
       * 武器类型	
       * </pre>
       */
      public int getWuqiType() {
        return wuqiType_;
      }
      /**
       * <code>required int32 wuqiType = 1;</code>
       *
       * <pre>
       * 武器类型	
       * </pre>
       */
      public Builder setWuqiType(int value) {
        bitField0_ |= 0x00000001;
        wuqiType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 wuqiType = 1;</code>
       *
       * <pre>
       * 武器类型	
       * </pre>
       */
      public Builder clearWuqiType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        wuqiType_ = 0;
        onChanged();
        return this;
      }

      // required int32 jinengType = 2;
      private int jinengType_ ;
      /**
       * <code>required int32 jinengType = 2;</code>
       *
       * <pre>
       * 技能类型	
       * </pre>
       */
      public boolean hasJinengType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 jinengType = 2;</code>
       *
       * <pre>
       * 技能类型	
       * </pre>
       */
      public int getJinengType() {
        return jinengType_;
      }
      /**
       * <code>required int32 jinengType = 2;</code>
       *
       * <pre>
       * 技能类型	
       * </pre>
       */
      public Builder setJinengType(int value) {
        bitField0_ |= 0x00000002;
        jinengType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 jinengType = 2;</code>
       *
       * <pre>
       * 技能类型	
       * </pre>
       */
      public Builder clearJinengType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jinengType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.UpgradeJiNengReq)
    }

    static {
      defaultInstance = new UpgradeJiNengReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.UpgradeJiNengReq)
  }

  public interface UpgradeJiNengRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 result = 1;
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     * 返回结果，0成功，1-失败
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     * 返回结果，0成功，1-失败
     * </pre>
     */
    int getResult();

    // optional string errorMsg = 2;
    /**
     * <code>optional string errorMsg = 2;</code>
     *
     * <pre>
     * 失败原因
     * </pre>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional string errorMsg = 2;</code>
     *
     * <pre>
     * 失败原因
     * </pre>
     */
    java.lang.String getErrorMsg();
    /**
     * <code>optional string errorMsg = 2;</code>
     *
     * <pre>
     * 失败原因
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.UpgradeJiNengResp}
   *
   * <pre>
   * 突破技能响应，协议号4253
   * </pre>
   */
  public static final class UpgradeJiNengResp extends
      com.google.protobuf.GeneratedMessage
      implements UpgradeJiNengRespOrBuilder {
    // Use UpgradeJiNengResp.newBuilder() to construct.
    private UpgradeJiNengResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UpgradeJiNengResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UpgradeJiNengResp defaultInstance;
    public static UpgradeJiNengResp getDefaultInstance() {
      return defaultInstance;
    }

    public UpgradeJiNengResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UpgradeJiNengResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errorMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_UpgradeJiNengResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_UpgradeJiNengResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp.class, qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp.Builder.class);
    }

    public static com.google.protobuf.Parser<UpgradeJiNengResp> PARSER =
        new com.google.protobuf.AbstractParser<UpgradeJiNengResp>() {
      public UpgradeJiNengResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpgradeJiNengResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UpgradeJiNengResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     * 返回结果，0成功，1-失败
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     * 返回结果，0成功，1-失败
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    // optional string errorMsg = 2;
    public static final int ERRORMSG_FIELD_NUMBER = 2;
    private java.lang.Object errorMsg_;
    /**
     * <code>optional string errorMsg = 2;</code>
     *
     * <pre>
     * 失败原因
     * </pre>
     */
    public boolean hasErrorMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string errorMsg = 2;</code>
     *
     * <pre>
     * 失败原因
     * </pre>
     */
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMsg = 2;</code>
     *
     * <pre>
     * 失败原因
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      result_ = 0;
      errorMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrorMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrorMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.UpgradeJiNengResp}
     *
     * <pre>
     * 突破技能响应，协议号4253
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_UpgradeJiNengResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_UpgradeJiNengResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp.class, qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp.Builder.class);
      }

      // Construct using qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.JiNengPeiYang.internal_static_qxmobile_protobuf_UpgradeJiNengResp_descriptor;
      }

      public qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp getDefaultInstanceForType() {
        return qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp.getDefaultInstance();
      }

      public qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp build() {
        qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp buildPartial() {
        qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp result = new qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorMsg_ = errorMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp) {
          return mergeFrom((qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp other) {
        if (other == qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasErrorMsg()) {
          bitField0_ |= 0x00000002;
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.JiNengPeiYang.UpgradeJiNengResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 result = 1;
      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       * 返回结果，0成功，1-失败
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       * 返回结果，0成功，1-失败
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       * 返回结果，0成功，1-失败
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       * 返回结果，0成功，1-失败
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // optional string errorMsg = 2;
      private java.lang.Object errorMsg_ = "";
      /**
       * <code>optional string errorMsg = 2;</code>
       *
       * <pre>
       * 失败原因
       * </pre>
       */
      public boolean hasErrorMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string errorMsg = 2;</code>
       *
       * <pre>
       * 失败原因
       * </pre>
       */
      public java.lang.String getErrorMsg() {
        java.lang.Object ref = errorMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMsg = 2;</code>
       *
       * <pre>
       * 失败原因
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        java.lang.Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMsg = 2;</code>
       *
       * <pre>
       * 失败原因
       * </pre>
       */
      public Builder setErrorMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMsg = 2;</code>
       *
       * <pre>
       * 失败原因
       * </pre>
       */
      public Builder clearErrorMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMsg = 2;</code>
       *
       * <pre>
       * 失败原因
       * </pre>
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.UpgradeJiNengResp)
    }

    static {
      defaultInstance = new UpgradeJiNengResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.UpgradeJiNengResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_GetJiNengPeiYangQuality_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_GetJiNengPeiYangQuality_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_JiNengQuality_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_JiNengQuality_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_UpgradeJiNengReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_UpgradeJiNengReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_UpgradeJiNengResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_UpgradeJiNengResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023JiNengPeiYang.proto\022\021qxmobile.protobuf" +
      "\"G\n\027GetJiNengPeiYangQuality\022,\n\002jn\030\001 \003(\0132" +
      " .qxmobile.protobuf.JiNengQuality\"F\n\rJiN" +
      "engQuality\022\020\n\010wuqiType\030\001 \002(\005\022\022\n\njinengTy" +
      "pe\030\002 \002(\005\022\017\n\007quality\030\003 \002(\005\"8\n\020UpgradeJiNe" +
      "ngReq\022\020\n\010wuqiType\030\001 \002(\005\022\022\n\njinengType\030\002 " +
      "\002(\005\"5\n\021UpgradeJiNengResp\022\016\n\006result\030\001 \002(\005" +
      "\022\020\n\010errorMsg\030\002 \001(\tB\017B\rJiNengPeiYang"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_qxmobile_protobuf_GetJiNengPeiYangQuality_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_qxmobile_protobuf_GetJiNengPeiYangQuality_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_GetJiNengPeiYangQuality_descriptor,
              new java.lang.String[] { "Jn", });
          internal_static_qxmobile_protobuf_JiNengQuality_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_qxmobile_protobuf_JiNengQuality_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_JiNengQuality_descriptor,
              new java.lang.String[] { "WuqiType", "JinengType", "Quality", });
          internal_static_qxmobile_protobuf_UpgradeJiNengReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_qxmobile_protobuf_UpgradeJiNengReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_UpgradeJiNengReq_descriptor,
              new java.lang.String[] { "WuqiType", "JinengType", });
          internal_static_qxmobile_protobuf_UpgradeJiNengResp_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_qxmobile_protobuf_UpgradeJiNengResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_UpgradeJiNengResp_descriptor,
              new java.lang.String[] { "Result", "ErrorMsg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
