// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JunzhuInfo.proto

package qxmobile.protobuf;

public final class JunzhuInfo {
  private JunzhuInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LevelReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 junzhuId = 1;
    /**
     * <code>required int64 junzhuId = 1;</code>
     */
    boolean hasJunzhuId();
    /**
     * <code>required int64 junzhuId = 1;</code>
     */
    long getJunzhuId();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.LevelReq}
   */
  public static final class LevelReq extends
      com.google.protobuf.GeneratedMessage
      implements LevelReqOrBuilder {
    // Use LevelReq.newBuilder() to construct.
    private LevelReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LevelReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LevelReq defaultInstance;
    public static LevelReq getDefaultInstance() {
      return defaultInstance;
    }

    public LevelReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LevelReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              junzhuId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.JunzhuInfo.internal_static_qxmobile_protobuf_LevelReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.JunzhuInfo.internal_static_qxmobile_protobuf_LevelReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.JunzhuInfo.LevelReq.class, qxmobile.protobuf.JunzhuInfo.LevelReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LevelReq> PARSER =
        new com.google.protobuf.AbstractParser<LevelReq>() {
      public LevelReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LevelReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LevelReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 junzhuId = 1;
    public static final int JUNZHUID_FIELD_NUMBER = 1;
    private long junzhuId_;
    /**
     * <code>required int64 junzhuId = 1;</code>
     */
    public boolean hasJunzhuId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 junzhuId = 1;</code>
     */
    public long getJunzhuId() {
      return junzhuId_;
    }

    private void initFields() {
      junzhuId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasJunzhuId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, junzhuId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, junzhuId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.JunzhuInfo.LevelReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.JunzhuInfo.LevelReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.LevelReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.JunzhuInfo.LevelReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.JunzhuInfo.internal_static_qxmobile_protobuf_LevelReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.JunzhuInfo.internal_static_qxmobile_protobuf_LevelReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.JunzhuInfo.LevelReq.class, qxmobile.protobuf.JunzhuInfo.LevelReq.Builder.class);
      }

      // Construct using qxmobile.protobuf.JunzhuInfo.LevelReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        junzhuId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.JunzhuInfo.internal_static_qxmobile_protobuf_LevelReq_descriptor;
      }

      public qxmobile.protobuf.JunzhuInfo.LevelReq getDefaultInstanceForType() {
        return qxmobile.protobuf.JunzhuInfo.LevelReq.getDefaultInstance();
      }

      public qxmobile.protobuf.JunzhuInfo.LevelReq build() {
        qxmobile.protobuf.JunzhuInfo.LevelReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.JunzhuInfo.LevelReq buildPartial() {
        qxmobile.protobuf.JunzhuInfo.LevelReq result = new qxmobile.protobuf.JunzhuInfo.LevelReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.junzhuId_ = junzhuId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.JunzhuInfo.LevelReq) {
          return mergeFrom((qxmobile.protobuf.JunzhuInfo.LevelReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.JunzhuInfo.LevelReq other) {
        if (other == qxmobile.protobuf.JunzhuInfo.LevelReq.getDefaultInstance()) return this;
        if (other.hasJunzhuId()) {
          setJunzhuId(other.getJunzhuId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasJunzhuId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.JunzhuInfo.LevelReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.JunzhuInfo.LevelReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 junzhuId = 1;
      private long junzhuId_ ;
      /**
       * <code>required int64 junzhuId = 1;</code>
       */
      public boolean hasJunzhuId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 junzhuId = 1;</code>
       */
      public long getJunzhuId() {
        return junzhuId_;
      }
      /**
       * <code>required int64 junzhuId = 1;</code>
       */
      public Builder setJunzhuId(long value) {
        bitField0_ |= 0x00000001;
        junzhuId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 junzhuId = 1;</code>
       */
      public Builder clearJunzhuId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        junzhuId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.LevelReq)
    }

    static {
      defaultInstance = new LevelReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.LevelReq)
  }

  public interface LevelRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 junzhuId = 1;
    /**
     * <code>required int64 junzhuId = 1;</code>
     */
    boolean hasJunzhuId();
    /**
     * <code>required int64 junzhuId = 1;</code>
     */
    long getJunzhuId();

    // required int32 junzhuLevel = 2;
    /**
     * <code>required int32 junzhuLevel = 2;</code>
     */
    boolean hasJunzhuLevel();
    /**
     * <code>required int32 junzhuLevel = 2;</code>
     */
    int getJunzhuLevel();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.LevelResp}
   */
  public static final class LevelResp extends
      com.google.protobuf.GeneratedMessage
      implements LevelRespOrBuilder {
    // Use LevelResp.newBuilder() to construct.
    private LevelResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LevelResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LevelResp defaultInstance;
    public static LevelResp getDefaultInstance() {
      return defaultInstance;
    }

    public LevelResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LevelResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              junzhuId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              junzhuLevel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.JunzhuInfo.internal_static_qxmobile_protobuf_LevelResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.JunzhuInfo.internal_static_qxmobile_protobuf_LevelResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.JunzhuInfo.LevelResp.class, qxmobile.protobuf.JunzhuInfo.LevelResp.Builder.class);
    }

    public static com.google.protobuf.Parser<LevelResp> PARSER =
        new com.google.protobuf.AbstractParser<LevelResp>() {
      public LevelResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LevelResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LevelResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 junzhuId = 1;
    public static final int JUNZHUID_FIELD_NUMBER = 1;
    private long junzhuId_;
    /**
     * <code>required int64 junzhuId = 1;</code>
     */
    public boolean hasJunzhuId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 junzhuId = 1;</code>
     */
    public long getJunzhuId() {
      return junzhuId_;
    }

    // required int32 junzhuLevel = 2;
    public static final int JUNZHULEVEL_FIELD_NUMBER = 2;
    private int junzhuLevel_;
    /**
     * <code>required int32 junzhuLevel = 2;</code>
     */
    public boolean hasJunzhuLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 junzhuLevel = 2;</code>
     */
    public int getJunzhuLevel() {
      return junzhuLevel_;
    }

    private void initFields() {
      junzhuId_ = 0L;
      junzhuLevel_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasJunzhuId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJunzhuLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, junzhuId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, junzhuLevel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, junzhuId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, junzhuLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.JunzhuInfo.LevelResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.JunzhuInfo.LevelResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.JunzhuInfo.LevelResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.LevelResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.JunzhuInfo.LevelRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.JunzhuInfo.internal_static_qxmobile_protobuf_LevelResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.JunzhuInfo.internal_static_qxmobile_protobuf_LevelResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.JunzhuInfo.LevelResp.class, qxmobile.protobuf.JunzhuInfo.LevelResp.Builder.class);
      }

      // Construct using qxmobile.protobuf.JunzhuInfo.LevelResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        junzhuId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        junzhuLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.JunzhuInfo.internal_static_qxmobile_protobuf_LevelResp_descriptor;
      }

      public qxmobile.protobuf.JunzhuInfo.LevelResp getDefaultInstanceForType() {
        return qxmobile.protobuf.JunzhuInfo.LevelResp.getDefaultInstance();
      }

      public qxmobile.protobuf.JunzhuInfo.LevelResp build() {
        qxmobile.protobuf.JunzhuInfo.LevelResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.JunzhuInfo.LevelResp buildPartial() {
        qxmobile.protobuf.JunzhuInfo.LevelResp result = new qxmobile.protobuf.JunzhuInfo.LevelResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.junzhuId_ = junzhuId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.junzhuLevel_ = junzhuLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.JunzhuInfo.LevelResp) {
          return mergeFrom((qxmobile.protobuf.JunzhuInfo.LevelResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.JunzhuInfo.LevelResp other) {
        if (other == qxmobile.protobuf.JunzhuInfo.LevelResp.getDefaultInstance()) return this;
        if (other.hasJunzhuId()) {
          setJunzhuId(other.getJunzhuId());
        }
        if (other.hasJunzhuLevel()) {
          setJunzhuLevel(other.getJunzhuLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasJunzhuId()) {
          
          return false;
        }
        if (!hasJunzhuLevel()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.JunzhuInfo.LevelResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.JunzhuInfo.LevelResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 junzhuId = 1;
      private long junzhuId_ ;
      /**
       * <code>required int64 junzhuId = 1;</code>
       */
      public boolean hasJunzhuId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 junzhuId = 1;</code>
       */
      public long getJunzhuId() {
        return junzhuId_;
      }
      /**
       * <code>required int64 junzhuId = 1;</code>
       */
      public Builder setJunzhuId(long value) {
        bitField0_ |= 0x00000001;
        junzhuId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 junzhuId = 1;</code>
       */
      public Builder clearJunzhuId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        junzhuId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 junzhuLevel = 2;
      private int junzhuLevel_ ;
      /**
       * <code>required int32 junzhuLevel = 2;</code>
       */
      public boolean hasJunzhuLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 junzhuLevel = 2;</code>
       */
      public int getJunzhuLevel() {
        return junzhuLevel_;
      }
      /**
       * <code>required int32 junzhuLevel = 2;</code>
       */
      public Builder setJunzhuLevel(int value) {
        bitField0_ |= 0x00000002;
        junzhuLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 junzhuLevel = 2;</code>
       */
      public Builder clearJunzhuLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        junzhuLevel_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.LevelResp)
    }

    static {
      defaultInstance = new LevelResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.LevelResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_LevelReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_LevelReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_LevelResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_LevelResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020JunzhuInfo.proto\022\021qxmobile.protobuf\"\034\n" +
      "\010LevelReq\022\020\n\010junzhuId\030\001 \002(\003\"2\n\tLevelResp" +
      "\022\020\n\010junzhuId\030\001 \002(\003\022\023\n\013junzhuLevel\030\002 \002(\005B" +
      "\014B\nJunzhuInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_qxmobile_protobuf_LevelReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_qxmobile_protobuf_LevelReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_LevelReq_descriptor,
              new java.lang.String[] { "JunzhuId", });
          internal_static_qxmobile_protobuf_LevelResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_qxmobile_protobuf_LevelResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_LevelResp_descriptor,
              new java.lang.String[] { "JunzhuId", "JunzhuLevel", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
