// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nActionResult.proto

package qxmobile.protobuf;

public final class NActionResultProtos {
  private NActionResultProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NActionResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 result = 1;
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     *0为成功，  1为失败
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     *0为成功，  1为失败
     * </pre>
     */
    int getResult();

    // required string account = 2;
    /**
     * <code>required string account = 2;</code>
     */
    boolean hasAccount();
    /**
     * <code>required string account = 2;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>required string account = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    // required int32 actionType = 3;
    /**
     * <code>required int32 actionType = 3;</code>
     *
     * <pre>
     * 1 攻占 2 修补
     * </pre>
     */
    boolean hasActionType();
    /**
     * <code>required int32 actionType = 3;</code>
     *
     * <pre>
     * 1 攻占 2 修补
     * </pre>
     */
    int getActionType();

    // required int32 cityId = 4;
    /**
     * <code>required int32 cityId = 4;</code>
     *
     * <pre>
     * 城池ID
     * </pre>
     */
    boolean hasCityId();
    /**
     * <code>required int32 cityId = 4;</code>
     *
     * <pre>
     * 城池ID
     * </pre>
     */
    int getCityId();

    // required int32 getZhanGong = 5;
    /**
     * <code>required int32 getZhanGong = 5;</code>
     *
     * <pre>
     * 获得的战功值
     * </pre>
     */
    boolean hasGetZhanGong();
    /**
     * <code>required int32 getZhanGong = 5;</code>
     *
     * <pre>
     * 获得的战功值
     * </pre>
     */
    int getGetZhanGong();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.NActionResult}
   */
  public static final class NActionResult extends
      com.google.protobuf.GeneratedMessage
      implements NActionResultOrBuilder {
    // Use NActionResult.newBuilder() to construct.
    private NActionResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NActionResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NActionResult defaultInstance;
    public static NActionResult getDefaultInstance() {
      return defaultInstance;
    }

    public NActionResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NActionResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              account_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              actionType_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              cityId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              getZhanGong_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.NActionResultProtos.internal_static_qxmobile_protobuf_NActionResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.NActionResultProtos.internal_static_qxmobile_protobuf_NActionResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.NActionResultProtos.NActionResult.class, qxmobile.protobuf.NActionResultProtos.NActionResult.Builder.class);
    }

    public static com.google.protobuf.Parser<NActionResult> PARSER =
        new com.google.protobuf.AbstractParser<NActionResult>() {
      public NActionResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NActionResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NActionResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     *0为成功，  1为失败
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     *0为成功，  1为失败
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    // required string account = 2;
    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private java.lang.Object account_;
    /**
     * <code>required string account = 2;</code>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string account = 2;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string account = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 actionType = 3;
    public static final int ACTIONTYPE_FIELD_NUMBER = 3;
    private int actionType_;
    /**
     * <code>required int32 actionType = 3;</code>
     *
     * <pre>
     * 1 攻占 2 修补
     * </pre>
     */
    public boolean hasActionType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 actionType = 3;</code>
     *
     * <pre>
     * 1 攻占 2 修补
     * </pre>
     */
    public int getActionType() {
      return actionType_;
    }

    // required int32 cityId = 4;
    public static final int CITYID_FIELD_NUMBER = 4;
    private int cityId_;
    /**
     * <code>required int32 cityId = 4;</code>
     *
     * <pre>
     * 城池ID
     * </pre>
     */
    public boolean hasCityId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 cityId = 4;</code>
     *
     * <pre>
     * 城池ID
     * </pre>
     */
    public int getCityId() {
      return cityId_;
    }

    // required int32 getZhanGong = 5;
    public static final int GETZHANGONG_FIELD_NUMBER = 5;
    private int getZhanGong_;
    /**
     * <code>required int32 getZhanGong = 5;</code>
     *
     * <pre>
     * 获得的战功值
     * </pre>
     */
    public boolean hasGetZhanGong() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 getZhanGong = 5;</code>
     *
     * <pre>
     * 获得的战功值
     * </pre>
     */
    public int getGetZhanGong() {
      return getZhanGong_;
    }

    private void initFields() {
      result_ = 0;
      account_ = "";
      actionType_ = 0;
      cityId_ = 0;
      getZhanGong_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActionType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCityId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGetZhanGong()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, actionType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, cityId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, getZhanGong_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, actionType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, cityId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getZhanGong_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.NActionResultProtos.NActionResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.NActionResultProtos.NActionResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.NActionResultProtos.NActionResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.NActionResultProtos.NActionResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.NActionResultProtos.NActionResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.NActionResultProtos.NActionResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.NActionResultProtos.NActionResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.NActionResultProtos.NActionResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.NActionResultProtos.NActionResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.NActionResultProtos.NActionResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.NActionResultProtos.NActionResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.NActionResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.NActionResultProtos.NActionResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.NActionResultProtos.internal_static_qxmobile_protobuf_NActionResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.NActionResultProtos.internal_static_qxmobile_protobuf_NActionResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.NActionResultProtos.NActionResult.class, qxmobile.protobuf.NActionResultProtos.NActionResult.Builder.class);
      }

      // Construct using qxmobile.protobuf.NActionResultProtos.NActionResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        actionType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        cityId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        getZhanGong_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.NActionResultProtos.internal_static_qxmobile_protobuf_NActionResult_descriptor;
      }

      public qxmobile.protobuf.NActionResultProtos.NActionResult getDefaultInstanceForType() {
        return qxmobile.protobuf.NActionResultProtos.NActionResult.getDefaultInstance();
      }

      public qxmobile.protobuf.NActionResultProtos.NActionResult build() {
        qxmobile.protobuf.NActionResultProtos.NActionResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.NActionResultProtos.NActionResult buildPartial() {
        qxmobile.protobuf.NActionResultProtos.NActionResult result = new qxmobile.protobuf.NActionResultProtos.NActionResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.actionType_ = actionType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cityId_ = cityId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.getZhanGong_ = getZhanGong_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.NActionResultProtos.NActionResult) {
          return mergeFrom((qxmobile.protobuf.NActionResultProtos.NActionResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.NActionResultProtos.NActionResult other) {
        if (other == qxmobile.protobuf.NActionResultProtos.NActionResult.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasAccount()) {
          bitField0_ |= 0x00000002;
          account_ = other.account_;
          onChanged();
        }
        if (other.hasActionType()) {
          setActionType(other.getActionType());
        }
        if (other.hasCityId()) {
          setCityId(other.getCityId());
        }
        if (other.hasGetZhanGong()) {
          setGetZhanGong(other.getGetZhanGong());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        if (!hasAccount()) {
          
          return false;
        }
        if (!hasActionType()) {
          
          return false;
        }
        if (!hasCityId()) {
          
          return false;
        }
        if (!hasGetZhanGong()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.NActionResultProtos.NActionResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.NActionResultProtos.NActionResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 result = 1;
      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       *0为成功，  1为失败
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       *0为成功，  1为失败
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       *0为成功，  1为失败
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       *0为成功，  1为失败
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // required string account = 2;
      private java.lang.Object account_ = "";
      /**
       * <code>required string account = 2;</code>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string account = 2;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string account = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string account = 2;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string account = 2;</code>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>required string account = 2;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }

      // required int32 actionType = 3;
      private int actionType_ ;
      /**
       * <code>required int32 actionType = 3;</code>
       *
       * <pre>
       * 1 攻占 2 修补
       * </pre>
       */
      public boolean hasActionType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 actionType = 3;</code>
       *
       * <pre>
       * 1 攻占 2 修补
       * </pre>
       */
      public int getActionType() {
        return actionType_;
      }
      /**
       * <code>required int32 actionType = 3;</code>
       *
       * <pre>
       * 1 攻占 2 修补
       * </pre>
       */
      public Builder setActionType(int value) {
        bitField0_ |= 0x00000004;
        actionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 actionType = 3;</code>
       *
       * <pre>
       * 1 攻占 2 修补
       * </pre>
       */
      public Builder clearActionType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        actionType_ = 0;
        onChanged();
        return this;
      }

      // required int32 cityId = 4;
      private int cityId_ ;
      /**
       * <code>required int32 cityId = 4;</code>
       *
       * <pre>
       * 城池ID
       * </pre>
       */
      public boolean hasCityId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 cityId = 4;</code>
       *
       * <pre>
       * 城池ID
       * </pre>
       */
      public int getCityId() {
        return cityId_;
      }
      /**
       * <code>required int32 cityId = 4;</code>
       *
       * <pre>
       * 城池ID
       * </pre>
       */
      public Builder setCityId(int value) {
        bitField0_ |= 0x00000008;
        cityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cityId = 4;</code>
       *
       * <pre>
       * 城池ID
       * </pre>
       */
      public Builder clearCityId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cityId_ = 0;
        onChanged();
        return this;
      }

      // required int32 getZhanGong = 5;
      private int getZhanGong_ ;
      /**
       * <code>required int32 getZhanGong = 5;</code>
       *
       * <pre>
       * 获得的战功值
       * </pre>
       */
      public boolean hasGetZhanGong() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 getZhanGong = 5;</code>
       *
       * <pre>
       * 获得的战功值
       * </pre>
       */
      public int getGetZhanGong() {
        return getZhanGong_;
      }
      /**
       * <code>required int32 getZhanGong = 5;</code>
       *
       * <pre>
       * 获得的战功值
       * </pre>
       */
      public Builder setGetZhanGong(int value) {
        bitField0_ |= 0x00000010;
        getZhanGong_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 getZhanGong = 5;</code>
       *
       * <pre>
       * 获得的战功值
       * </pre>
       */
      public Builder clearGetZhanGong() {
        bitField0_ = (bitField0_ & ~0x00000010);
        getZhanGong_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.NActionResult)
    }

    static {
      defaultInstance = new NActionResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.NActionResult)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_NActionResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_NActionResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023nActionResult.proto\022\021qxmobile.protobuf" +
      "\"i\n\rNActionResult\022\016\n\006result\030\001 \002(\005\022\017\n\007acc" +
      "ount\030\002 \002(\t\022\022\n\nactionType\030\003 \002(\005\022\016\n\006cityId" +
      "\030\004 \002(\005\022\023\n\013getZhanGong\030\005 \002(\005B\025B\023NActionRe" +
      "sultProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_qxmobile_protobuf_NActionResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_qxmobile_protobuf_NActionResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_NActionResult_descriptor,
              new java.lang.String[] { "Result", "Account", "ActionType", "CityId", "GetZhanGong", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
