// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nCheckReport.proto

package qxmobile.protobuf;

public final class NCheckReportProtos {
  private NCheckReportProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NCheckReportOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string account = 1;
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     * 玩家帐户
     * </pre>
     */
    boolean hasAccount();
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     * 玩家帐户
     * </pre>
     */
    java.lang.String getAccount();
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     * 玩家帐户
     * </pre>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    // required int32 actId = 2;
    /**
     * <code>required int32 actId = 2;</code>
     *
     * <pre>
     * 0：为进入；1：为退出
     * </pre>
     */
    boolean hasActId();
    /**
     * <code>required int32 actId = 2;</code>
     *
     * <pre>
     * 0：为进入；1：为退出
     * </pre>
     */
    int getActId();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.NCheckReport}
   */
  public static final class NCheckReport extends
      com.google.protobuf.GeneratedMessage
      implements NCheckReportOrBuilder {
    // Use NCheckReport.newBuilder() to construct.
    private NCheckReport(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NCheckReport(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NCheckReport defaultInstance;
    public static NCheckReport getDefaultInstance() {
      return defaultInstance;
    }

    public NCheckReport getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NCheckReport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              account_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              actId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.NCheckReportProtos.internal_static_qxmobile_protobuf_NCheckReport_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.NCheckReportProtos.internal_static_qxmobile_protobuf_NCheckReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.NCheckReportProtos.NCheckReport.class, qxmobile.protobuf.NCheckReportProtos.NCheckReport.Builder.class);
    }

    public static com.google.protobuf.Parser<NCheckReport> PARSER =
        new com.google.protobuf.AbstractParser<NCheckReport>() {
      public NCheckReport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NCheckReport(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NCheckReport> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private java.lang.Object account_;
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     * 玩家帐户
     * </pre>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     * 玩家帐户
     * </pre>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     * 玩家帐户
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 actId = 2;
    public static final int ACTID_FIELD_NUMBER = 2;
    private int actId_;
    /**
     * <code>required int32 actId = 2;</code>
     *
     * <pre>
     * 0：为进入；1：为退出
     * </pre>
     */
    public boolean hasActId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 actId = 2;</code>
     *
     * <pre>
     * 0：为进入；1：为退出
     * </pre>
     */
    public int getActId() {
      return actId_;
    }

    private void initFields() {
      account_ = "";
      actId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, actId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, actId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.NCheckReportProtos.NCheckReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.NCheckReportProtos.NCheckReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.NCheckReportProtos.NCheckReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.NCheckReportProtos.NCheckReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.NCheckReportProtos.NCheckReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.NCheckReportProtos.NCheckReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.NCheckReportProtos.NCheckReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.NCheckReportProtos.NCheckReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.NCheckReportProtos.NCheckReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.NCheckReportProtos.NCheckReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.NCheckReportProtos.NCheckReport prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.NCheckReport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.NCheckReportProtos.NCheckReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.NCheckReportProtos.internal_static_qxmobile_protobuf_NCheckReport_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.NCheckReportProtos.internal_static_qxmobile_protobuf_NCheckReport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.NCheckReportProtos.NCheckReport.class, qxmobile.protobuf.NCheckReportProtos.NCheckReport.Builder.class);
      }

      // Construct using qxmobile.protobuf.NCheckReportProtos.NCheckReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        actId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.NCheckReportProtos.internal_static_qxmobile_protobuf_NCheckReport_descriptor;
      }

      public qxmobile.protobuf.NCheckReportProtos.NCheckReport getDefaultInstanceForType() {
        return qxmobile.protobuf.NCheckReportProtos.NCheckReport.getDefaultInstance();
      }

      public qxmobile.protobuf.NCheckReportProtos.NCheckReport build() {
        qxmobile.protobuf.NCheckReportProtos.NCheckReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.NCheckReportProtos.NCheckReport buildPartial() {
        qxmobile.protobuf.NCheckReportProtos.NCheckReport result = new qxmobile.protobuf.NCheckReportProtos.NCheckReport(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.actId_ = actId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.NCheckReportProtos.NCheckReport) {
          return mergeFrom((qxmobile.protobuf.NCheckReportProtos.NCheckReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.NCheckReportProtos.NCheckReport other) {
        if (other == qxmobile.protobuf.NCheckReportProtos.NCheckReport.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          bitField0_ |= 0x00000001;
          account_ = other.account_;
          onChanged();
        }
        if (other.hasActId()) {
          setActId(other.getActId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccount()) {
          
          return false;
        }
        if (!hasActId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.NCheckReportProtos.NCheckReport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.NCheckReportProtos.NCheckReport) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string account = 1;
      private java.lang.Object account_ = "";
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       * 玩家帐户
       * </pre>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       * 玩家帐户
       * </pre>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       * 玩家帐户
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       * 玩家帐户
       * </pre>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       * 玩家帐户
       * </pre>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       * 玩家帐户
       * </pre>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
        return this;
      }

      // required int32 actId = 2;
      private int actId_ ;
      /**
       * <code>required int32 actId = 2;</code>
       *
       * <pre>
       * 0：为进入；1：为退出
       * </pre>
       */
      public boolean hasActId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 actId = 2;</code>
       *
       * <pre>
       * 0：为进入；1：为退出
       * </pre>
       */
      public int getActId() {
        return actId_;
      }
      /**
       * <code>required int32 actId = 2;</code>
       *
       * <pre>
       * 0：为进入；1：为退出
       * </pre>
       */
      public Builder setActId(int value) {
        bitField0_ |= 0x00000002;
        actId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 actId = 2;</code>
       *
       * <pre>
       * 0：为进入；1：为退出
       * </pre>
       */
      public Builder clearActId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        actId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.NCheckReport)
    }

    static {
      defaultInstance = new NCheckReport(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.NCheckReport)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_NCheckReport_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_NCheckReport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022nCheckReport.proto\022\021qxmobile.protobuf\"" +
      ".\n\014NCheckReport\022\017\n\007account\030\001 \002(\t\022\r\n\005actI" +
      "d\030\002 \002(\005B\024B\022NCheckReportProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_qxmobile_protobuf_NCheckReport_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_qxmobile_protobuf_NCheckReport_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_NCheckReport_descriptor,
              new java.lang.String[] { "Account", "ActId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
