// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package qxmobile.protobuf;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 userId = 1;
    /**
     * <code>required int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 1;</code>
     */
    int getUserId();

    // required string account = 2;
    /**
     * <code>required string account = 2;</code>
     */
    boolean hasAccount();
    /**
     * <code>required string account = 2;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>required string account = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    // required string userName = 3;
    /**
     * <code>required string userName = 3;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 3;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // required int32 level = 4;
    /**
     * <code>required int32 level = 4;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 4;</code>
     */
    int getLevel();

    // required int32 countryId = 5;
    /**
     * <code>required int32 countryId = 5;</code>
     */
    boolean hasCountryId();
    /**
     * <code>required int32 countryId = 5;</code>
     */
    int getCountryId();

    // required int32 heroIdGenerator = 6;
    /**
     * <code>required int32 heroIdGenerator = 6;</code>
     */
    boolean hasHeroIdGenerator();
    /**
     * <code>required int32 heroIdGenerator = 6;</code>
     */
    int getHeroIdGenerator();

    // required int32 itemIdGenerator = 7;
    /**
     * <code>required int32 itemIdGenerator = 7;</code>
     */
    boolean hasItemIdGenerator();
    /**
     * <code>required int32 itemIdGenerator = 7;</code>
     */
    int getItemIdGenerator();

    // required int32 buildingIdGenerator = 8;
    /**
     * <code>required int32 buildingIdGenerator = 8;</code>
     */
    boolean hasBuildingIdGenerator();
    /**
     * <code>required int32 buildingIdGenerator = 8;</code>
     */
    int getBuildingIdGenerator();

    // required int32 exp = 9;
    /**
     * <code>required int32 exp = 9;</code>
     */
    boolean hasExp();
    /**
     * <code>required int32 exp = 9;</code>
     */
    int getExp();

    // optional int32 guildId = 10;
    /**
     * <code>optional int32 guildId = 10;</code>
     */
    boolean hasGuildId();
    /**
     * <code>optional int32 guildId = 10;</code>
     */
    int getGuildId();

    // optional int32 guildDuty = 11;
    /**
     * <code>optional int32 guildDuty = 11;</code>
     */
    boolean hasGuildDuty();
    /**
     * <code>optional int32 guildDuty = 11;</code>
     */
    int getGuildDuty();

    // optional int32 maxFloorLv = 12;
    /**
     * <code>optional int32 maxFloorLv = 12;</code>
     */
    boolean hasMaxFloorLv();
    /**
     * <code>optional int32 maxFloorLv = 12;</code>
     */
    int getMaxFloorLv();

    // optional string qianMing = 13;
    /**
     * <code>optional string qianMing = 13;</code>
     */
    boolean hasQianMing();
    /**
     * <code>optional string qianMing = 13;</code>
     */
    java.lang.String getQianMing();
    /**
     * <code>optional string qianMing = 13;</code>
     */
    com.google.protobuf.ByteString
        getQianMingBytes();

    // optional int32 guanZhi = 14;
    /**
     * <code>optional int32 guanZhi = 14;</code>
     */
    boolean hasGuanZhi();
    /**
     * <code>optional int32 guanZhi = 14;</code>
     */
    int getGuanZhi();

    // optional int32 collectTime = 15;
    /**
     * <code>optional int32 collectTime = 15;</code>
     */
    boolean hasCollectTime();
    /**
     * <code>optional int32 collectTime = 15;</code>
     */
    int getCollectTime();

    // optional int32 guildMailVersion = 16;
    /**
     * <code>optional int32 guildMailVersion = 16;</code>
     */
    boolean hasGuildMailVersion();
    /**
     * <code>optional int32 guildMailVersion = 16;</code>
     */
    int getGuildMailVersion();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              account_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              userName_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              level_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              countryId_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              heroIdGenerator_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              itemIdGenerator_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              buildingIdGenerator_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              exp_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              guildId_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              guildDuty_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              maxFloorLv_ = input.readInt32();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              qianMing_ = input.readBytes();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              guanZhi_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              collectTime_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              guildMailVersion_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.UserProtos.internal_static_qxmobile_protobuf_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.UserProtos.internal_static_qxmobile_protobuf_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.UserProtos.User.class, qxmobile.protobuf.UserProtos.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // required string account = 2;
    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private java.lang.Object account_;
    /**
     * <code>required string account = 2;</code>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string account = 2;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string account = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string userName = 3;
    public static final int USERNAME_FIELD_NUMBER = 3;
    private java.lang.Object userName_;
    /**
     * <code>required string userName = 3;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string userName = 3;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 level = 4;
    public static final int LEVEL_FIELD_NUMBER = 4;
    private int level_;
    /**
     * <code>required int32 level = 4;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 level = 4;</code>
     */
    public int getLevel() {
      return level_;
    }

    // required int32 countryId = 5;
    public static final int COUNTRYID_FIELD_NUMBER = 5;
    private int countryId_;
    /**
     * <code>required int32 countryId = 5;</code>
     */
    public boolean hasCountryId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 countryId = 5;</code>
     */
    public int getCountryId() {
      return countryId_;
    }

    // required int32 heroIdGenerator = 6;
    public static final int HEROIDGENERATOR_FIELD_NUMBER = 6;
    private int heroIdGenerator_;
    /**
     * <code>required int32 heroIdGenerator = 6;</code>
     */
    public boolean hasHeroIdGenerator() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 heroIdGenerator = 6;</code>
     */
    public int getHeroIdGenerator() {
      return heroIdGenerator_;
    }

    // required int32 itemIdGenerator = 7;
    public static final int ITEMIDGENERATOR_FIELD_NUMBER = 7;
    private int itemIdGenerator_;
    /**
     * <code>required int32 itemIdGenerator = 7;</code>
     */
    public boolean hasItemIdGenerator() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 itemIdGenerator = 7;</code>
     */
    public int getItemIdGenerator() {
      return itemIdGenerator_;
    }

    // required int32 buildingIdGenerator = 8;
    public static final int BUILDINGIDGENERATOR_FIELD_NUMBER = 8;
    private int buildingIdGenerator_;
    /**
     * <code>required int32 buildingIdGenerator = 8;</code>
     */
    public boolean hasBuildingIdGenerator() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 buildingIdGenerator = 8;</code>
     */
    public int getBuildingIdGenerator() {
      return buildingIdGenerator_;
    }

    // required int32 exp = 9;
    public static final int EXP_FIELD_NUMBER = 9;
    private int exp_;
    /**
     * <code>required int32 exp = 9;</code>
     */
    public boolean hasExp() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 exp = 9;</code>
     */
    public int getExp() {
      return exp_;
    }

    // optional int32 guildId = 10;
    public static final int GUILDID_FIELD_NUMBER = 10;
    private int guildId_;
    /**
     * <code>optional int32 guildId = 10;</code>
     */
    public boolean hasGuildId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 guildId = 10;</code>
     */
    public int getGuildId() {
      return guildId_;
    }

    // optional int32 guildDuty = 11;
    public static final int GUILDDUTY_FIELD_NUMBER = 11;
    private int guildDuty_;
    /**
     * <code>optional int32 guildDuty = 11;</code>
     */
    public boolean hasGuildDuty() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 guildDuty = 11;</code>
     */
    public int getGuildDuty() {
      return guildDuty_;
    }

    // optional int32 maxFloorLv = 12;
    public static final int MAXFLOORLV_FIELD_NUMBER = 12;
    private int maxFloorLv_;
    /**
     * <code>optional int32 maxFloorLv = 12;</code>
     */
    public boolean hasMaxFloorLv() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 maxFloorLv = 12;</code>
     */
    public int getMaxFloorLv() {
      return maxFloorLv_;
    }

    // optional string qianMing = 13;
    public static final int QIANMING_FIELD_NUMBER = 13;
    private java.lang.Object qianMing_;
    /**
     * <code>optional string qianMing = 13;</code>
     */
    public boolean hasQianMing() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string qianMing = 13;</code>
     */
    public java.lang.String getQianMing() {
      java.lang.Object ref = qianMing_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          qianMing_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string qianMing = 13;</code>
     */
    public com.google.protobuf.ByteString
        getQianMingBytes() {
      java.lang.Object ref = qianMing_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        qianMing_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 guanZhi = 14;
    public static final int GUANZHI_FIELD_NUMBER = 14;
    private int guanZhi_;
    /**
     * <code>optional int32 guanZhi = 14;</code>
     */
    public boolean hasGuanZhi() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int32 guanZhi = 14;</code>
     */
    public int getGuanZhi() {
      return guanZhi_;
    }

    // optional int32 collectTime = 15;
    public static final int COLLECTTIME_FIELD_NUMBER = 15;
    private int collectTime_;
    /**
     * <code>optional int32 collectTime = 15;</code>
     */
    public boolean hasCollectTime() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int32 collectTime = 15;</code>
     */
    public int getCollectTime() {
      return collectTime_;
    }

    // optional int32 guildMailVersion = 16;
    public static final int GUILDMAILVERSION_FIELD_NUMBER = 16;
    private int guildMailVersion_;
    /**
     * <code>optional int32 guildMailVersion = 16;</code>
     */
    public boolean hasGuildMailVersion() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional int32 guildMailVersion = 16;</code>
     */
    public int getGuildMailVersion() {
      return guildMailVersion_;
    }

    private void initFields() {
      userId_ = 0;
      account_ = "";
      userName_ = "";
      level_ = 0;
      countryId_ = 0;
      heroIdGenerator_ = 0;
      itemIdGenerator_ = 0;
      buildingIdGenerator_ = 0;
      exp_ = 0;
      guildId_ = 0;
      guildDuty_ = 0;
      maxFloorLv_ = 0;
      qianMing_ = "";
      guanZhi_ = 0;
      collectTime_ = 0;
      guildMailVersion_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCountryId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeroIdGenerator()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasItemIdGenerator()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBuildingIdGenerator()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, level_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, countryId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, heroIdGenerator_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, itemIdGenerator_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, buildingIdGenerator_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, exp_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, guildId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, guildDuty_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, maxFloorLv_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getQianMingBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, guanZhi_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, collectTime_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(16, guildMailVersion_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, level_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, countryId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, heroIdGenerator_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, itemIdGenerator_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, buildingIdGenerator_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, exp_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, guildId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, guildDuty_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, maxFloorLv_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getQianMingBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, guanZhi_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, collectTime_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, guildMailVersion_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.UserProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.UserProtos.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.UserProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.UserProtos.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.UserProtos.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.UserProtos.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.UserProtos.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.UserProtos.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.UserProtos.internal_static_qxmobile_protobuf_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.UserProtos.internal_static_qxmobile_protobuf_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.UserProtos.User.class, qxmobile.protobuf.UserProtos.User.Builder.class);
      }

      // Construct using qxmobile.protobuf.UserProtos.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        countryId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        heroIdGenerator_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        itemIdGenerator_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        buildingIdGenerator_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        exp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        guildId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        guildDuty_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        maxFloorLv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        qianMing_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        guanZhi_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        collectTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        guildMailVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.UserProtos.internal_static_qxmobile_protobuf_User_descriptor;
      }

      public qxmobile.protobuf.UserProtos.User getDefaultInstanceForType() {
        return qxmobile.protobuf.UserProtos.User.getDefaultInstance();
      }

      public qxmobile.protobuf.UserProtos.User build() {
        qxmobile.protobuf.UserProtos.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.UserProtos.User buildPartial() {
        qxmobile.protobuf.UserProtos.User result = new qxmobile.protobuf.UserProtos.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.countryId_ = countryId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.heroIdGenerator_ = heroIdGenerator_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.itemIdGenerator_ = itemIdGenerator_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.buildingIdGenerator_ = buildingIdGenerator_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.exp_ = exp_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.guildId_ = guildId_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.guildDuty_ = guildDuty_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.maxFloorLv_ = maxFloorLv_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.qianMing_ = qianMing_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.guanZhi_ = guanZhi_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.collectTime_ = collectTime_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.guildMailVersion_ = guildMailVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.UserProtos.User) {
          return mergeFrom((qxmobile.protobuf.UserProtos.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.UserProtos.User other) {
        if (other == qxmobile.protobuf.UserProtos.User.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasAccount()) {
          bitField0_ |= 0x00000002;
          account_ = other.account_;
          onChanged();
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000004;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasCountryId()) {
          setCountryId(other.getCountryId());
        }
        if (other.hasHeroIdGenerator()) {
          setHeroIdGenerator(other.getHeroIdGenerator());
        }
        if (other.hasItemIdGenerator()) {
          setItemIdGenerator(other.getItemIdGenerator());
        }
        if (other.hasBuildingIdGenerator()) {
          setBuildingIdGenerator(other.getBuildingIdGenerator());
        }
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        if (other.hasGuildId()) {
          setGuildId(other.getGuildId());
        }
        if (other.hasGuildDuty()) {
          setGuildDuty(other.getGuildDuty());
        }
        if (other.hasMaxFloorLv()) {
          setMaxFloorLv(other.getMaxFloorLv());
        }
        if (other.hasQianMing()) {
          bitField0_ |= 0x00001000;
          qianMing_ = other.qianMing_;
          onChanged();
        }
        if (other.hasGuanZhi()) {
          setGuanZhi(other.getGuanZhi());
        }
        if (other.hasCollectTime()) {
          setCollectTime(other.getCollectTime());
        }
        if (other.hasGuildMailVersion()) {
          setGuildMailVersion(other.getGuildMailVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasAccount()) {
          
          return false;
        }
        if (!hasUserName()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasCountryId()) {
          
          return false;
        }
        if (!hasHeroIdGenerator()) {
          
          return false;
        }
        if (!hasItemIdGenerator()) {
          
          return false;
        }
        if (!hasBuildingIdGenerator()) {
          
          return false;
        }
        if (!hasExp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.UserProtos.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.UserProtos.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 userId = 1;
      private int userId_ ;
      /**
       * <code>required int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // required string account = 2;
      private java.lang.Object account_ = "";
      /**
       * <code>required string account = 2;</code>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string account = 2;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string account = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string account = 2;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string account = 2;</code>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>required string account = 2;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }

      // required string userName = 3;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 3;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userName_ = value;
        onChanged();
        return this;
      }

      // required int32 level = 4;
      private int level_ ;
      /**
       * <code>required int32 level = 4;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 level = 4;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 4;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000008;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 4;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        onChanged();
        return this;
      }

      // required int32 countryId = 5;
      private int countryId_ ;
      /**
       * <code>required int32 countryId = 5;</code>
       */
      public boolean hasCountryId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 countryId = 5;</code>
       */
      public int getCountryId() {
        return countryId_;
      }
      /**
       * <code>required int32 countryId = 5;</code>
       */
      public Builder setCountryId(int value) {
        bitField0_ |= 0x00000010;
        countryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 countryId = 5;</code>
       */
      public Builder clearCountryId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        countryId_ = 0;
        onChanged();
        return this;
      }

      // required int32 heroIdGenerator = 6;
      private int heroIdGenerator_ ;
      /**
       * <code>required int32 heroIdGenerator = 6;</code>
       */
      public boolean hasHeroIdGenerator() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 heroIdGenerator = 6;</code>
       */
      public int getHeroIdGenerator() {
        return heroIdGenerator_;
      }
      /**
       * <code>required int32 heroIdGenerator = 6;</code>
       */
      public Builder setHeroIdGenerator(int value) {
        bitField0_ |= 0x00000020;
        heroIdGenerator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 heroIdGenerator = 6;</code>
       */
      public Builder clearHeroIdGenerator() {
        bitField0_ = (bitField0_ & ~0x00000020);
        heroIdGenerator_ = 0;
        onChanged();
        return this;
      }

      // required int32 itemIdGenerator = 7;
      private int itemIdGenerator_ ;
      /**
       * <code>required int32 itemIdGenerator = 7;</code>
       */
      public boolean hasItemIdGenerator() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 itemIdGenerator = 7;</code>
       */
      public int getItemIdGenerator() {
        return itemIdGenerator_;
      }
      /**
       * <code>required int32 itemIdGenerator = 7;</code>
       */
      public Builder setItemIdGenerator(int value) {
        bitField0_ |= 0x00000040;
        itemIdGenerator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 itemIdGenerator = 7;</code>
       */
      public Builder clearItemIdGenerator() {
        bitField0_ = (bitField0_ & ~0x00000040);
        itemIdGenerator_ = 0;
        onChanged();
        return this;
      }

      // required int32 buildingIdGenerator = 8;
      private int buildingIdGenerator_ ;
      /**
       * <code>required int32 buildingIdGenerator = 8;</code>
       */
      public boolean hasBuildingIdGenerator() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 buildingIdGenerator = 8;</code>
       */
      public int getBuildingIdGenerator() {
        return buildingIdGenerator_;
      }
      /**
       * <code>required int32 buildingIdGenerator = 8;</code>
       */
      public Builder setBuildingIdGenerator(int value) {
        bitField0_ |= 0x00000080;
        buildingIdGenerator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 buildingIdGenerator = 8;</code>
       */
      public Builder clearBuildingIdGenerator() {
        bitField0_ = (bitField0_ & ~0x00000080);
        buildingIdGenerator_ = 0;
        onChanged();
        return this;
      }

      // required int32 exp = 9;
      private int exp_ ;
      /**
       * <code>required int32 exp = 9;</code>
       */
      public boolean hasExp() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 exp = 9;</code>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <code>required int32 exp = 9;</code>
       */
      public Builder setExp(int value) {
        bitField0_ |= 0x00000100;
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 exp = 9;</code>
       */
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000100);
        exp_ = 0;
        onChanged();
        return this;
      }

      // optional int32 guildId = 10;
      private int guildId_ ;
      /**
       * <code>optional int32 guildId = 10;</code>
       */
      public boolean hasGuildId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 guildId = 10;</code>
       */
      public int getGuildId() {
        return guildId_;
      }
      /**
       * <code>optional int32 guildId = 10;</code>
       */
      public Builder setGuildId(int value) {
        bitField0_ |= 0x00000200;
        guildId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 guildId = 10;</code>
       */
      public Builder clearGuildId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        guildId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 guildDuty = 11;
      private int guildDuty_ ;
      /**
       * <code>optional int32 guildDuty = 11;</code>
       */
      public boolean hasGuildDuty() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 guildDuty = 11;</code>
       */
      public int getGuildDuty() {
        return guildDuty_;
      }
      /**
       * <code>optional int32 guildDuty = 11;</code>
       */
      public Builder setGuildDuty(int value) {
        bitField0_ |= 0x00000400;
        guildDuty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 guildDuty = 11;</code>
       */
      public Builder clearGuildDuty() {
        bitField0_ = (bitField0_ & ~0x00000400);
        guildDuty_ = 0;
        onChanged();
        return this;
      }

      // optional int32 maxFloorLv = 12;
      private int maxFloorLv_ ;
      /**
       * <code>optional int32 maxFloorLv = 12;</code>
       */
      public boolean hasMaxFloorLv() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 maxFloorLv = 12;</code>
       */
      public int getMaxFloorLv() {
        return maxFloorLv_;
      }
      /**
       * <code>optional int32 maxFloorLv = 12;</code>
       */
      public Builder setMaxFloorLv(int value) {
        bitField0_ |= 0x00000800;
        maxFloorLv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 maxFloorLv = 12;</code>
       */
      public Builder clearMaxFloorLv() {
        bitField0_ = (bitField0_ & ~0x00000800);
        maxFloorLv_ = 0;
        onChanged();
        return this;
      }

      // optional string qianMing = 13;
      private java.lang.Object qianMing_ = "";
      /**
       * <code>optional string qianMing = 13;</code>
       */
      public boolean hasQianMing() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string qianMing = 13;</code>
       */
      public java.lang.String getQianMing() {
        java.lang.Object ref = qianMing_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          qianMing_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string qianMing = 13;</code>
       */
      public com.google.protobuf.ByteString
          getQianMingBytes() {
        java.lang.Object ref = qianMing_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          qianMing_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string qianMing = 13;</code>
       */
      public Builder setQianMing(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        qianMing_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string qianMing = 13;</code>
       */
      public Builder clearQianMing() {
        bitField0_ = (bitField0_ & ~0x00001000);
        qianMing_ = getDefaultInstance().getQianMing();
        onChanged();
        return this;
      }
      /**
       * <code>optional string qianMing = 13;</code>
       */
      public Builder setQianMingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        qianMing_ = value;
        onChanged();
        return this;
      }

      // optional int32 guanZhi = 14;
      private int guanZhi_ ;
      /**
       * <code>optional int32 guanZhi = 14;</code>
       */
      public boolean hasGuanZhi() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int32 guanZhi = 14;</code>
       */
      public int getGuanZhi() {
        return guanZhi_;
      }
      /**
       * <code>optional int32 guanZhi = 14;</code>
       */
      public Builder setGuanZhi(int value) {
        bitField0_ |= 0x00002000;
        guanZhi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 guanZhi = 14;</code>
       */
      public Builder clearGuanZhi() {
        bitField0_ = (bitField0_ & ~0x00002000);
        guanZhi_ = 0;
        onChanged();
        return this;
      }

      // optional int32 collectTime = 15;
      private int collectTime_ ;
      /**
       * <code>optional int32 collectTime = 15;</code>
       */
      public boolean hasCollectTime() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int32 collectTime = 15;</code>
       */
      public int getCollectTime() {
        return collectTime_;
      }
      /**
       * <code>optional int32 collectTime = 15;</code>
       */
      public Builder setCollectTime(int value) {
        bitField0_ |= 0x00004000;
        collectTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 collectTime = 15;</code>
       */
      public Builder clearCollectTime() {
        bitField0_ = (bitField0_ & ~0x00004000);
        collectTime_ = 0;
        onChanged();
        return this;
      }

      // optional int32 guildMailVersion = 16;
      private int guildMailVersion_ ;
      /**
       * <code>optional int32 guildMailVersion = 16;</code>
       */
      public boolean hasGuildMailVersion() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional int32 guildMailVersion = 16;</code>
       */
      public int getGuildMailVersion() {
        return guildMailVersion_;
      }
      /**
       * <code>optional int32 guildMailVersion = 16;</code>
       */
      public Builder setGuildMailVersion(int value) {
        bitField0_ |= 0x00008000;
        guildMailVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 guildMailVersion = 16;</code>
       */
      public Builder clearGuildMailVersion() {
        bitField0_ = (bitField0_ & ~0x00008000);
        guildMailVersion_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.User)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\021qxmobile.protobuf\"\301\002\n\004User" +
      "\022\016\n\006userId\030\001 \002(\005\022\017\n\007account\030\002 \002(\t\022\020\n\010use" +
      "rName\030\003 \002(\t\022\r\n\005level\030\004 \002(\005\022\021\n\tcountryId\030" +
      "\005 \002(\005\022\027\n\017heroIdGenerator\030\006 \002(\005\022\027\n\017itemId" +
      "Generator\030\007 \002(\005\022\033\n\023buildingIdGenerator\030\010" +
      " \002(\005\022\013\n\003exp\030\t \002(\005\022\017\n\007guildId\030\n \001(\005\022\021\n\tgu" +
      "ildDuty\030\013 \001(\005\022\022\n\nmaxFloorLv\030\014 \001(\005\022\020\n\010qia" +
      "nMing\030\r \001(\t\022\017\n\007guanZhi\030\016 \001(\005\022\023\n\013collectT" +
      "ime\030\017 \001(\005\022\030\n\020guildMailVersion\030\020 \001(\005B\014B\nU" +
      "serProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_qxmobile_protobuf_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_qxmobile_protobuf_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_User_descriptor,
              new java.lang.String[] { "UserId", "Account", "UserName", "Level", "CountryId", "HeroIdGenerator", "ItemIdGenerator", "BuildingIdGenerator", "Exp", "GuildId", "GuildDuty", "MaxFloorLv", "QianMing", "GuanZhi", "CollectTime", "GuildMailVersion", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
