// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VIP.proto

package qxmobile.protobuf;

public final class VIP {
  private VIP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RechargeReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 type = 1;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 充值类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 充值类型
     * </pre>
     */
    int getType();

    // required int32 amount = 2;
    /**
     * <code>required int32 amount = 2;</code>
     *
     * <pre>
     * 本次充值金额，人民币数
     * </pre>
     */
    boolean hasAmount();
    /**
     * <code>required int32 amount = 2;</code>
     *
     * <pre>
     * 本次充值金额，人民币数
     * </pre>
     */
    int getAmount();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.RechargeReq}
   */
  public static final class RechargeReq extends
      com.google.protobuf.GeneratedMessage
      implements RechargeReqOrBuilder {
    // Use RechargeReq.newBuilder() to construct.
    private RechargeReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RechargeReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RechargeReq defaultInstance;
    public static RechargeReq getDefaultInstance() {
      return defaultInstance;
    }

    public RechargeReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RechargeReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              amount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_RechargeReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_RechargeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.VIP.RechargeReq.class, qxmobile.protobuf.VIP.RechargeReq.Builder.class);
    }

    public static com.google.protobuf.Parser<RechargeReq> PARSER =
        new com.google.protobuf.AbstractParser<RechargeReq>() {
      public RechargeReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RechargeReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RechargeReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 充值类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 充值类型
     * </pre>
     */
    public int getType() {
      return type_;
    }

    // required int32 amount = 2;
    public static final int AMOUNT_FIELD_NUMBER = 2;
    private int amount_;
    /**
     * <code>required int32 amount = 2;</code>
     *
     * <pre>
     * 本次充值金额，人民币数
     * </pre>
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 amount = 2;</code>
     *
     * <pre>
     * 本次充值金额，人民币数
     * </pre>
     */
    public int getAmount() {
      return amount_;
    }

    private void initFields() {
      type_ = 0;
      amount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, amount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, amount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.VIP.RechargeReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.VIP.RechargeReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.RechargeReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.VIP.RechargeReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.RechargeReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.VIP.RechargeReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.RechargeReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.VIP.RechargeReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.RechargeReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.VIP.RechargeReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.VIP.RechargeReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.RechargeReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.VIP.RechargeReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_RechargeReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_RechargeReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.VIP.RechargeReq.class, qxmobile.protobuf.VIP.RechargeReq.Builder.class);
      }

      // Construct using qxmobile.protobuf.VIP.RechargeReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        amount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_RechargeReq_descriptor;
      }

      public qxmobile.protobuf.VIP.RechargeReq getDefaultInstanceForType() {
        return qxmobile.protobuf.VIP.RechargeReq.getDefaultInstance();
      }

      public qxmobile.protobuf.VIP.RechargeReq build() {
        qxmobile.protobuf.VIP.RechargeReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.VIP.RechargeReq buildPartial() {
        qxmobile.protobuf.VIP.RechargeReq result = new qxmobile.protobuf.VIP.RechargeReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.amount_ = amount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.VIP.RechargeReq) {
          return mergeFrom((qxmobile.protobuf.VIP.RechargeReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.VIP.RechargeReq other) {
        if (other == qxmobile.protobuf.VIP.RechargeReq.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasAmount()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.VIP.RechargeReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.VIP.RechargeReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 type = 1;
      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 充值类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 充值类型
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 充值类型
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 充值类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      // required int32 amount = 2;
      private int amount_ ;
      /**
       * <code>required int32 amount = 2;</code>
       *
       * <pre>
       * 本次充值金额，人民币数
       * </pre>
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 amount = 2;</code>
       *
       * <pre>
       * 本次充值金额，人民币数
       * </pre>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>required int32 amount = 2;</code>
       *
       * <pre>
       * 本次充值金额，人民币数
       * </pre>
       */
      public Builder setAmount(int value) {
        bitField0_ |= 0x00000002;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 amount = 2;</code>
       *
       * <pre>
       * 本次充值金额，人民币数
       * </pre>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        amount_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.RechargeReq)
    }

    static {
      defaultInstance = new RechargeReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.RechargeReq)
  }

  public interface RechargeRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool isSuccess = 1;
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    boolean hasIsSuccess();
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    boolean getIsSuccess();

    // required int32 sumAoumnt = 2;
    /**
     * <code>required int32 sumAoumnt = 2;</code>
     *
     * <pre>
     * 本次充值增加的元宝数
     * </pre>
     */
    boolean hasSumAoumnt();
    /**
     * <code>required int32 sumAoumnt = 2;</code>
     *
     * <pre>
     * 本次充值增加的元宝数
     * </pre>
     */
    int getSumAoumnt();

    // required int32 vipLevel = 3;
    /**
     * <code>required int32 vipLevel = 3;</code>
     *
     * <pre>
     * vip等级
     * </pre>
     */
    boolean hasVipLevel();
    /**
     * <code>required int32 vipLevel = 3;</code>
     *
     * <pre>
     * vip等级
     * </pre>
     */
    int getVipLevel();

    // optional int32 yueKaLeftDays = 4;
    /**
     * <code>optional int32 yueKaLeftDays = 4;</code>
     */
    boolean hasYueKaLeftDays();
    /**
     * <code>optional int32 yueKaLeftDays = 4;</code>
     */
    int getYueKaLeftDays();

    // optional string msg = 5;
    /**
     * <code>optional string msg = 5;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 5;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 5;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.RechargeResp}
   */
  public static final class RechargeResp extends
      com.google.protobuf.GeneratedMessage
      implements RechargeRespOrBuilder {
    // Use RechargeResp.newBuilder() to construct.
    private RechargeResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RechargeResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RechargeResp defaultInstance;
    public static RechargeResp getDefaultInstance() {
      return defaultInstance;
    }

    public RechargeResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RechargeResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isSuccess_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sumAoumnt_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              vipLevel_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              yueKaLeftDays_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_RechargeResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_RechargeResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.VIP.RechargeResp.class, qxmobile.protobuf.VIP.RechargeResp.Builder.class);
    }

    public static com.google.protobuf.Parser<RechargeResp> PARSER =
        new com.google.protobuf.AbstractParser<RechargeResp>() {
      public RechargeResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RechargeResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RechargeResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool isSuccess = 1;
    public static final int ISSUCCESS_FIELD_NUMBER = 1;
    private boolean isSuccess_;
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    // required int32 sumAoumnt = 2;
    public static final int SUMAOUMNT_FIELD_NUMBER = 2;
    private int sumAoumnt_;
    /**
     * <code>required int32 sumAoumnt = 2;</code>
     *
     * <pre>
     * 本次充值增加的元宝数
     * </pre>
     */
    public boolean hasSumAoumnt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 sumAoumnt = 2;</code>
     *
     * <pre>
     * 本次充值增加的元宝数
     * </pre>
     */
    public int getSumAoumnt() {
      return sumAoumnt_;
    }

    // required int32 vipLevel = 3;
    public static final int VIPLEVEL_FIELD_NUMBER = 3;
    private int vipLevel_;
    /**
     * <code>required int32 vipLevel = 3;</code>
     *
     * <pre>
     * vip等级
     * </pre>
     */
    public boolean hasVipLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 vipLevel = 3;</code>
     *
     * <pre>
     * vip等级
     * </pre>
     */
    public int getVipLevel() {
      return vipLevel_;
    }

    // optional int32 yueKaLeftDays = 4;
    public static final int YUEKALEFTDAYS_FIELD_NUMBER = 4;
    private int yueKaLeftDays_;
    /**
     * <code>optional int32 yueKaLeftDays = 4;</code>
     */
    public boolean hasYueKaLeftDays() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 yueKaLeftDays = 4;</code>
     */
    public int getYueKaLeftDays() {
      return yueKaLeftDays_;
    }

    // optional string msg = 5;
    public static final int MSG_FIELD_NUMBER = 5;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 5;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string msg = 5;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      isSuccess_ = false;
      sumAoumnt_ = 0;
      vipLevel_ = 0;
      yueKaLeftDays_ = 0;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSumAoumnt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVipLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sumAoumnt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, vipLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, yueKaLeftDays_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sumAoumnt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, vipLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, yueKaLeftDays_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.VIP.RechargeResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.VIP.RechargeResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.RechargeResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.VIP.RechargeResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.RechargeResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.VIP.RechargeResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.RechargeResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.VIP.RechargeResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.RechargeResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.VIP.RechargeResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.VIP.RechargeResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.RechargeResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.VIP.RechargeRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_RechargeResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_RechargeResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.VIP.RechargeResp.class, qxmobile.protobuf.VIP.RechargeResp.Builder.class);
      }

      // Construct using qxmobile.protobuf.VIP.RechargeResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        sumAoumnt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        vipLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        yueKaLeftDays_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_RechargeResp_descriptor;
      }

      public qxmobile.protobuf.VIP.RechargeResp getDefaultInstanceForType() {
        return qxmobile.protobuf.VIP.RechargeResp.getDefaultInstance();
      }

      public qxmobile.protobuf.VIP.RechargeResp build() {
        qxmobile.protobuf.VIP.RechargeResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.VIP.RechargeResp buildPartial() {
        qxmobile.protobuf.VIP.RechargeResp result = new qxmobile.protobuf.VIP.RechargeResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isSuccess_ = isSuccess_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sumAoumnt_ = sumAoumnt_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.vipLevel_ = vipLevel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.yueKaLeftDays_ = yueKaLeftDays_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.VIP.RechargeResp) {
          return mergeFrom((qxmobile.protobuf.VIP.RechargeResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.VIP.RechargeResp other) {
        if (other == qxmobile.protobuf.VIP.RechargeResp.getDefaultInstance()) return this;
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        if (other.hasSumAoumnt()) {
          setSumAoumnt(other.getSumAoumnt());
        }
        if (other.hasVipLevel()) {
          setVipLevel(other.getVipLevel());
        }
        if (other.hasYueKaLeftDays()) {
          setYueKaLeftDays(other.getYueKaLeftDays());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000010;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsSuccess()) {
          
          return false;
        }
        if (!hasSumAoumnt()) {
          
          return false;
        }
        if (!hasVipLevel()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.VIP.RechargeResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.VIP.RechargeResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool isSuccess = 1;
      private boolean isSuccess_ ;
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      // required int32 sumAoumnt = 2;
      private int sumAoumnt_ ;
      /**
       * <code>required int32 sumAoumnt = 2;</code>
       *
       * <pre>
       * 本次充值增加的元宝数
       * </pre>
       */
      public boolean hasSumAoumnt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 sumAoumnt = 2;</code>
       *
       * <pre>
       * 本次充值增加的元宝数
       * </pre>
       */
      public int getSumAoumnt() {
        return sumAoumnt_;
      }
      /**
       * <code>required int32 sumAoumnt = 2;</code>
       *
       * <pre>
       * 本次充值增加的元宝数
       * </pre>
       */
      public Builder setSumAoumnt(int value) {
        bitField0_ |= 0x00000002;
        sumAoumnt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sumAoumnt = 2;</code>
       *
       * <pre>
       * 本次充值增加的元宝数
       * </pre>
       */
      public Builder clearSumAoumnt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sumAoumnt_ = 0;
        onChanged();
        return this;
      }

      // required int32 vipLevel = 3;
      private int vipLevel_ ;
      /**
       * <code>required int32 vipLevel = 3;</code>
       *
       * <pre>
       * vip等级
       * </pre>
       */
      public boolean hasVipLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 vipLevel = 3;</code>
       *
       * <pre>
       * vip等级
       * </pre>
       */
      public int getVipLevel() {
        return vipLevel_;
      }
      /**
       * <code>required int32 vipLevel = 3;</code>
       *
       * <pre>
       * vip等级
       * </pre>
       */
      public Builder setVipLevel(int value) {
        bitField0_ |= 0x00000004;
        vipLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 vipLevel = 3;</code>
       *
       * <pre>
       * vip等级
       * </pre>
       */
      public Builder clearVipLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        vipLevel_ = 0;
        onChanged();
        return this;
      }

      // optional int32 yueKaLeftDays = 4;
      private int yueKaLeftDays_ ;
      /**
       * <code>optional int32 yueKaLeftDays = 4;</code>
       */
      public boolean hasYueKaLeftDays() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 yueKaLeftDays = 4;</code>
       */
      public int getYueKaLeftDays() {
        return yueKaLeftDays_;
      }
      /**
       * <code>optional int32 yueKaLeftDays = 4;</code>
       */
      public Builder setYueKaLeftDays(int value) {
        bitField0_ |= 0x00000008;
        yueKaLeftDays_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 yueKaLeftDays = 4;</code>
       */
      public Builder clearYueKaLeftDays() {
        bitField0_ = (bitField0_ & ~0x00000008);
        yueKaLeftDays_ = 0;
        onChanged();
        return this;
      }

      // optional string msg = 5;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 5;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.RechargeResp)
    }

    static {
      defaultInstance = new RechargeResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.RechargeResp)
  }

  public interface VipInfoRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 vipLevel = 1;
    /**
     * <code>required int32 vipLevel = 1;</code>
     */
    boolean hasVipLevel();
    /**
     * <code>required int32 vipLevel = 1;</code>
     */
    int getVipLevel();

    // required int32 needYb = 2;
    /**
     * <code>required int32 needYb = 2;</code>
     */
    boolean hasNeedYb();
    /**
     * <code>required int32 needYb = 2;</code>
     */
    int getNeedYb();

    // required int32 hasYb = 3;
    /**
     * <code>required int32 hasYb = 3;</code>
     */
    boolean hasHasYb();
    /**
     * <code>required int32 hasYb = 3;</code>
     */
    int getHasYb();

    // required bool isMax = 4;
    /**
     * <code>required bool isMax = 4;</code>
     *
     * <pre>
     * 是否vip等级已经达到最高
     * </pre>
     */
    boolean hasIsMax();
    /**
     * <code>required bool isMax = 4;</code>
     *
     * <pre>
     * 是否vip等级已经达到最高
     * </pre>
     */
    boolean getIsMax();

    // repeated .qxmobile.protobuf.ChongTimes infos = 5;
    /**
     * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
     */
    java.util.List<qxmobile.protobuf.VIP.ChongTimes> 
        getInfosList();
    /**
     * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
     */
    qxmobile.protobuf.VIP.ChongTimes getInfos(int index);
    /**
     * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
     */
    int getInfosCount();
    /**
     * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
     */
    java.util.List<? extends qxmobile.protobuf.VIP.ChongTimesOrBuilder> 
        getInfosOrBuilderList();
    /**
     * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
     */
    qxmobile.protobuf.VIP.ChongTimesOrBuilder getInfosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.VipInfoResp}
   *
   * <pre>
   * 充值页面
   * </pre>
   */
  public static final class VipInfoResp extends
      com.google.protobuf.GeneratedMessage
      implements VipInfoRespOrBuilder {
    // Use VipInfoResp.newBuilder() to construct.
    private VipInfoResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VipInfoResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VipInfoResp defaultInstance;
    public static VipInfoResp getDefaultInstance() {
      return defaultInstance;
    }

    public VipInfoResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VipInfoResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              vipLevel_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              needYb_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              hasYb_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isMax_ = input.readBool();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                infos_ = new java.util.ArrayList<qxmobile.protobuf.VIP.ChongTimes>();
                mutable_bitField0_ |= 0x00000010;
              }
              infos_.add(input.readMessage(qxmobile.protobuf.VIP.ChongTimes.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          infos_ = java.util.Collections.unmodifiableList(infos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_VipInfoResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_VipInfoResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.VIP.VipInfoResp.class, qxmobile.protobuf.VIP.VipInfoResp.Builder.class);
    }

    public static com.google.protobuf.Parser<VipInfoResp> PARSER =
        new com.google.protobuf.AbstractParser<VipInfoResp>() {
      public VipInfoResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VipInfoResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VipInfoResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 vipLevel = 1;
    public static final int VIPLEVEL_FIELD_NUMBER = 1;
    private int vipLevel_;
    /**
     * <code>required int32 vipLevel = 1;</code>
     */
    public boolean hasVipLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 vipLevel = 1;</code>
     */
    public int getVipLevel() {
      return vipLevel_;
    }

    // required int32 needYb = 2;
    public static final int NEEDYB_FIELD_NUMBER = 2;
    private int needYb_;
    /**
     * <code>required int32 needYb = 2;</code>
     */
    public boolean hasNeedYb() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 needYb = 2;</code>
     */
    public int getNeedYb() {
      return needYb_;
    }

    // required int32 hasYb = 3;
    public static final int HASYB_FIELD_NUMBER = 3;
    private int hasYb_;
    /**
     * <code>required int32 hasYb = 3;</code>
     */
    public boolean hasHasYb() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 hasYb = 3;</code>
     */
    public int getHasYb() {
      return hasYb_;
    }

    // required bool isMax = 4;
    public static final int ISMAX_FIELD_NUMBER = 4;
    private boolean isMax_;
    /**
     * <code>required bool isMax = 4;</code>
     *
     * <pre>
     * 是否vip等级已经达到最高
     * </pre>
     */
    public boolean hasIsMax() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool isMax = 4;</code>
     *
     * <pre>
     * 是否vip等级已经达到最高
     * </pre>
     */
    public boolean getIsMax() {
      return isMax_;
    }

    // repeated .qxmobile.protobuf.ChongTimes infos = 5;
    public static final int INFOS_FIELD_NUMBER = 5;
    private java.util.List<qxmobile.protobuf.VIP.ChongTimes> infos_;
    /**
     * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
     */
    public java.util.List<qxmobile.protobuf.VIP.ChongTimes> getInfosList() {
      return infos_;
    }
    /**
     * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
     */
    public java.util.List<? extends qxmobile.protobuf.VIP.ChongTimesOrBuilder> 
        getInfosOrBuilderList() {
      return infos_;
    }
    /**
     * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
     */
    public int getInfosCount() {
      return infos_.size();
    }
    /**
     * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
     */
    public qxmobile.protobuf.VIP.ChongTimes getInfos(int index) {
      return infos_.get(index);
    }
    /**
     * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
     */
    public qxmobile.protobuf.VIP.ChongTimesOrBuilder getInfosOrBuilder(
        int index) {
      return infos_.get(index);
    }

    private void initFields() {
      vipLevel_ = 0;
      needYb_ = 0;
      hasYb_ = 0;
      isMax_ = false;
      infos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVipLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNeedYb()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHasYb()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsMax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getInfosCount(); i++) {
        if (!getInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, vipLevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, needYb_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, hasYb_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isMax_);
      }
      for (int i = 0; i < infos_.size(); i++) {
        output.writeMessage(5, infos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, vipLevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, needYb_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, hasYb_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isMax_);
      }
      for (int i = 0; i < infos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, infos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.VIP.VipInfoResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.VIP.VipInfoResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.VipInfoResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.VIP.VipInfoResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.VipInfoResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.VIP.VipInfoResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.VipInfoResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.VIP.VipInfoResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.VipInfoResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.VIP.VipInfoResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.VIP.VipInfoResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.VipInfoResp}
     *
     * <pre>
     * 充值页面
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.VIP.VipInfoRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_VipInfoResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_VipInfoResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.VIP.VipInfoResp.class, qxmobile.protobuf.VIP.VipInfoResp.Builder.class);
      }

      // Construct using qxmobile.protobuf.VIP.VipInfoResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        vipLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        needYb_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        hasYb_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        isMax_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          infosBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_VipInfoResp_descriptor;
      }

      public qxmobile.protobuf.VIP.VipInfoResp getDefaultInstanceForType() {
        return qxmobile.protobuf.VIP.VipInfoResp.getDefaultInstance();
      }

      public qxmobile.protobuf.VIP.VipInfoResp build() {
        qxmobile.protobuf.VIP.VipInfoResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.VIP.VipInfoResp buildPartial() {
        qxmobile.protobuf.VIP.VipInfoResp result = new qxmobile.protobuf.VIP.VipInfoResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.vipLevel_ = vipLevel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.needYb_ = needYb_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hasYb_ = hasYb_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isMax_ = isMax_;
        if (infosBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            infos_ = java.util.Collections.unmodifiableList(infos_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.infos_ = infos_;
        } else {
          result.infos_ = infosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.VIP.VipInfoResp) {
          return mergeFrom((qxmobile.protobuf.VIP.VipInfoResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.VIP.VipInfoResp other) {
        if (other == qxmobile.protobuf.VIP.VipInfoResp.getDefaultInstance()) return this;
        if (other.hasVipLevel()) {
          setVipLevel(other.getVipLevel());
        }
        if (other.hasNeedYb()) {
          setNeedYb(other.getNeedYb());
        }
        if (other.hasHasYb()) {
          setHasYb(other.getHasYb());
        }
        if (other.hasIsMax()) {
          setIsMax(other.getIsMax());
        }
        if (infosBuilder_ == null) {
          if (!other.infos_.isEmpty()) {
            if (infos_.isEmpty()) {
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureInfosIsMutable();
              infos_.addAll(other.infos_);
            }
            onChanged();
          }
        } else {
          if (!other.infos_.isEmpty()) {
            if (infosBuilder_.isEmpty()) {
              infosBuilder_.dispose();
              infosBuilder_ = null;
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000010);
              infosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInfosFieldBuilder() : null;
            } else {
              infosBuilder_.addAllMessages(other.infos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVipLevel()) {
          
          return false;
        }
        if (!hasNeedYb()) {
          
          return false;
        }
        if (!hasHasYb()) {
          
          return false;
        }
        if (!hasIsMax()) {
          
          return false;
        }
        for (int i = 0; i < getInfosCount(); i++) {
          if (!getInfos(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.VIP.VipInfoResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.VIP.VipInfoResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 vipLevel = 1;
      private int vipLevel_ ;
      /**
       * <code>required int32 vipLevel = 1;</code>
       */
      public boolean hasVipLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 vipLevel = 1;</code>
       */
      public int getVipLevel() {
        return vipLevel_;
      }
      /**
       * <code>required int32 vipLevel = 1;</code>
       */
      public Builder setVipLevel(int value) {
        bitField0_ |= 0x00000001;
        vipLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 vipLevel = 1;</code>
       */
      public Builder clearVipLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        vipLevel_ = 0;
        onChanged();
        return this;
      }

      // required int32 needYb = 2;
      private int needYb_ ;
      /**
       * <code>required int32 needYb = 2;</code>
       */
      public boolean hasNeedYb() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 needYb = 2;</code>
       */
      public int getNeedYb() {
        return needYb_;
      }
      /**
       * <code>required int32 needYb = 2;</code>
       */
      public Builder setNeedYb(int value) {
        bitField0_ |= 0x00000002;
        needYb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 needYb = 2;</code>
       */
      public Builder clearNeedYb() {
        bitField0_ = (bitField0_ & ~0x00000002);
        needYb_ = 0;
        onChanged();
        return this;
      }

      // required int32 hasYb = 3;
      private int hasYb_ ;
      /**
       * <code>required int32 hasYb = 3;</code>
       */
      public boolean hasHasYb() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 hasYb = 3;</code>
       */
      public int getHasYb() {
        return hasYb_;
      }
      /**
       * <code>required int32 hasYb = 3;</code>
       */
      public Builder setHasYb(int value) {
        bitField0_ |= 0x00000004;
        hasYb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 hasYb = 3;</code>
       */
      public Builder clearHasYb() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hasYb_ = 0;
        onChanged();
        return this;
      }

      // required bool isMax = 4;
      private boolean isMax_ ;
      /**
       * <code>required bool isMax = 4;</code>
       *
       * <pre>
       * 是否vip等级已经达到最高
       * </pre>
       */
      public boolean hasIsMax() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool isMax = 4;</code>
       *
       * <pre>
       * 是否vip等级已经达到最高
       * </pre>
       */
      public boolean getIsMax() {
        return isMax_;
      }
      /**
       * <code>required bool isMax = 4;</code>
       *
       * <pre>
       * 是否vip等级已经达到最高
       * </pre>
       */
      public Builder setIsMax(boolean value) {
        bitField0_ |= 0x00000008;
        isMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isMax = 4;</code>
       *
       * <pre>
       * 是否vip等级已经达到最高
       * </pre>
       */
      public Builder clearIsMax() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isMax_ = false;
        onChanged();
        return this;
      }

      // repeated .qxmobile.protobuf.ChongTimes infos = 5;
      private java.util.List<qxmobile.protobuf.VIP.ChongTimes> infos_ =
        java.util.Collections.emptyList();
      private void ensureInfosIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          infos_ = new java.util.ArrayList<qxmobile.protobuf.VIP.ChongTimes>(infos_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          qxmobile.protobuf.VIP.ChongTimes, qxmobile.protobuf.VIP.ChongTimes.Builder, qxmobile.protobuf.VIP.ChongTimesOrBuilder> infosBuilder_;

      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public java.util.List<qxmobile.protobuf.VIP.ChongTimes> getInfosList() {
        if (infosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(infos_);
        } else {
          return infosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public int getInfosCount() {
        if (infosBuilder_ == null) {
          return infos_.size();
        } else {
          return infosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public qxmobile.protobuf.VIP.ChongTimes getInfos(int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);
        } else {
          return infosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public Builder setInfos(
          int index, qxmobile.protobuf.VIP.ChongTimes value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.set(index, value);
          onChanged();
        } else {
          infosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public Builder setInfos(
          int index, qxmobile.protobuf.VIP.ChongTimes.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.set(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public Builder addInfos(qxmobile.protobuf.VIP.ChongTimes value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(value);
          onChanged();
        } else {
          infosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public Builder addInfos(
          int index, qxmobile.protobuf.VIP.ChongTimes value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(index, value);
          onChanged();
        } else {
          infosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public Builder addInfos(
          qxmobile.protobuf.VIP.ChongTimes.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public Builder addInfos(
          int index, qxmobile.protobuf.VIP.ChongTimes.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public Builder addAllInfos(
          java.lang.Iterable<? extends qxmobile.protobuf.VIP.ChongTimes> values) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          super.addAll(values, infos_);
          onChanged();
        } else {
          infosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public Builder clearInfos() {
        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          infosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public Builder removeInfos(int index) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.remove(index);
          onChanged();
        } else {
          infosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public qxmobile.protobuf.VIP.ChongTimes.Builder getInfosBuilder(
          int index) {
        return getInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public qxmobile.protobuf.VIP.ChongTimesOrBuilder getInfosOrBuilder(
          int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);  } else {
          return infosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public java.util.List<? extends qxmobile.protobuf.VIP.ChongTimesOrBuilder> 
           getInfosOrBuilderList() {
        if (infosBuilder_ != null) {
          return infosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(infos_);
        }
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public qxmobile.protobuf.VIP.ChongTimes.Builder addInfosBuilder() {
        return getInfosFieldBuilder().addBuilder(
            qxmobile.protobuf.VIP.ChongTimes.getDefaultInstance());
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public qxmobile.protobuf.VIP.ChongTimes.Builder addInfosBuilder(
          int index) {
        return getInfosFieldBuilder().addBuilder(
            index, qxmobile.protobuf.VIP.ChongTimes.getDefaultInstance());
      }
      /**
       * <code>repeated .qxmobile.protobuf.ChongTimes infos = 5;</code>
       */
      public java.util.List<qxmobile.protobuf.VIP.ChongTimes.Builder> 
           getInfosBuilderList() {
        return getInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          qxmobile.protobuf.VIP.ChongTimes, qxmobile.protobuf.VIP.ChongTimes.Builder, qxmobile.protobuf.VIP.ChongTimesOrBuilder> 
          getInfosFieldBuilder() {
        if (infosBuilder_ == null) {
          infosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              qxmobile.protobuf.VIP.ChongTimes, qxmobile.protobuf.VIP.ChongTimes.Builder, qxmobile.protobuf.VIP.ChongTimesOrBuilder>(
                  infos_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          infos_ = null;
        }
        return infosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.VipInfoResp)
    }

    static {
      defaultInstance = new VipInfoResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.VipInfoResp)
  }

  public interface ChongTimesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required int32 times = 2;
    /**
     * <code>required int32 times = 2;</code>
     *
     * <pre>
     * 已充值的次数
     * </pre>
     */
    boolean hasTimes();
    /**
     * <code>required int32 times = 2;</code>
     *
     * <pre>
     * 已充值的次数
     * </pre>
     */
    int getTimes();
  }
  /**
   * Protobuf type {@code qxmobile.protobuf.ChongTimes}
   */
  public static final class ChongTimes extends
      com.google.protobuf.GeneratedMessage
      implements ChongTimesOrBuilder {
    // Use ChongTimes.newBuilder() to construct.
    private ChongTimes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChongTimes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChongTimes defaultInstance;
    public static ChongTimes getDefaultInstance() {
      return defaultInstance;
    }

    public ChongTimes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChongTimes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              times_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_ChongTimes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_ChongTimes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qxmobile.protobuf.VIP.ChongTimes.class, qxmobile.protobuf.VIP.ChongTimes.Builder.class);
    }

    public static com.google.protobuf.Parser<ChongTimes> PARSER =
        new com.google.protobuf.AbstractParser<ChongTimes>() {
      public ChongTimes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChongTimes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChongTimes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required int32 times = 2;
    public static final int TIMES_FIELD_NUMBER = 2;
    private int times_;
    /**
     * <code>required int32 times = 2;</code>
     *
     * <pre>
     * 已充值的次数
     * </pre>
     */
    public boolean hasTimes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 times = 2;</code>
     *
     * <pre>
     * 已充值的次数
     * </pre>
     */
    public int getTimes() {
      return times_;
    }

    private void initFields() {
      id_ = 0;
      times_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, times_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, times_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qxmobile.protobuf.VIP.ChongTimes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.VIP.ChongTimes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.ChongTimes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qxmobile.protobuf.VIP.ChongTimes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.ChongTimes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.VIP.ChongTimes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.ChongTimes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qxmobile.protobuf.VIP.ChongTimes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qxmobile.protobuf.VIP.ChongTimes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qxmobile.protobuf.VIP.ChongTimes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qxmobile.protobuf.VIP.ChongTimes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qxmobile.protobuf.ChongTimes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qxmobile.protobuf.VIP.ChongTimesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_ChongTimes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_ChongTimes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qxmobile.protobuf.VIP.ChongTimes.class, qxmobile.protobuf.VIP.ChongTimes.Builder.class);
      }

      // Construct using qxmobile.protobuf.VIP.ChongTimes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        times_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qxmobile.protobuf.VIP.internal_static_qxmobile_protobuf_ChongTimes_descriptor;
      }

      public qxmobile.protobuf.VIP.ChongTimes getDefaultInstanceForType() {
        return qxmobile.protobuf.VIP.ChongTimes.getDefaultInstance();
      }

      public qxmobile.protobuf.VIP.ChongTimes build() {
        qxmobile.protobuf.VIP.ChongTimes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qxmobile.protobuf.VIP.ChongTimes buildPartial() {
        qxmobile.protobuf.VIP.ChongTimes result = new qxmobile.protobuf.VIP.ChongTimes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.times_ = times_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qxmobile.protobuf.VIP.ChongTimes) {
          return mergeFrom((qxmobile.protobuf.VIP.ChongTimes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qxmobile.protobuf.VIP.ChongTimes other) {
        if (other == qxmobile.protobuf.VIP.ChongTimes.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTimes()) {
          setTimes(other.getTimes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasTimes()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qxmobile.protobuf.VIP.ChongTimes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qxmobile.protobuf.VIP.ChongTimes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required int32 times = 2;
      private int times_ ;
      /**
       * <code>required int32 times = 2;</code>
       *
       * <pre>
       * 已充值的次数
       * </pre>
       */
      public boolean hasTimes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 times = 2;</code>
       *
       * <pre>
       * 已充值的次数
       * </pre>
       */
      public int getTimes() {
        return times_;
      }
      /**
       * <code>required int32 times = 2;</code>
       *
       * <pre>
       * 已充值的次数
       * </pre>
       */
      public Builder setTimes(int value) {
        bitField0_ |= 0x00000002;
        times_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 times = 2;</code>
       *
       * <pre>
       * 已充值的次数
       * </pre>
       */
      public Builder clearTimes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        times_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qxmobile.protobuf.ChongTimes)
    }

    static {
      defaultInstance = new ChongTimes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qxmobile.protobuf.ChongTimes)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_RechargeReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_RechargeReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_RechargeResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_RechargeResp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_VipInfoResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_VipInfoResp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qxmobile_protobuf_ChongTimes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qxmobile_protobuf_ChongTimes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tVIP.proto\022\021qxmobile.protobuf\"+\n\013Rechar" +
      "geReq\022\014\n\004type\030\001 \002(\005\022\016\n\006amount\030\002 \002(\005\"j\n\014R" +
      "echargeResp\022\021\n\tisSuccess\030\001 \002(\010\022\021\n\tsumAou" +
      "mnt\030\002 \002(\005\022\020\n\010vipLevel\030\003 \002(\005\022\025\n\ryueKaLeft" +
      "Days\030\004 \001(\005\022\013\n\003msg\030\005 \001(\t\"{\n\013VipInfoResp\022\020" +
      "\n\010vipLevel\030\001 \002(\005\022\016\n\006needYb\030\002 \002(\005\022\r\n\005hasY" +
      "b\030\003 \002(\005\022\r\n\005isMax\030\004 \002(\010\022,\n\005infos\030\005 \003(\0132\035." +
      "qxmobile.protobuf.ChongTimes\"\'\n\nChongTim" +
      "es\022\n\n\002id\030\001 \002(\005\022\r\n\005times\030\002 \002(\005B\005B\003VIP"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_qxmobile_protobuf_RechargeReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_qxmobile_protobuf_RechargeReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_RechargeReq_descriptor,
              new java.lang.String[] { "Type", "Amount", });
          internal_static_qxmobile_protobuf_RechargeResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_qxmobile_protobuf_RechargeResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_RechargeResp_descriptor,
              new java.lang.String[] { "IsSuccess", "SumAoumnt", "VipLevel", "YueKaLeftDays", "Msg", });
          internal_static_qxmobile_protobuf_VipInfoResp_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_qxmobile_protobuf_VipInfoResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_VipInfoResp_descriptor,
              new java.lang.String[] { "VipLevel", "NeedYb", "HasYb", "IsMax", "Infos", });
          internal_static_qxmobile_protobuf_ChongTimes_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_qxmobile_protobuf_ChongTimes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qxmobile_protobuf_ChongTimes_descriptor,
              new java.lang.String[] { "Id", "Times", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
